/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

import ConnectDatabase.DatabaseConnection;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import javax.swing.JOptionPane;

import java.util.List;
import static jdk.nashorn.internal.objects.NativeRegExp.source;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;

/**
 *
 * @author shannon
 */
public class clientFeedback extends javax.swing.JFrame{
    
    /**
     * Creates new form clientFeedback
     */

    Connection con = null; 
    PreparedStatement pst = null;
    ResultSet rs = null;
     
    int count=0;
     int psum=0;int sum=0;
     
     
     
    public clientFeedback() {
        initComponents();
        
         con=DatabaseConnection.connect();
         
         clients();
    
    }
    
    
    public void jobs(){
       String query1;
        try{
                      
            String CID = cid.getSelectedItem().toString();
            Statement sts = con.createStatement();
            query1= "SELECT TACID FROM jobtac j where j.client='" +CID+ "';";
            ResultSet rst = sts.executeQuery(query1);
            
            jid1.removeAllItems();
            jid1.addItem("Select");
            
            while(rst.next()){
            jid1.addItem(rst.getString(1));
            }
        }
        catch(Exception ex){
            System.out.println(ex+"sad");
        }
    }
    
    public void clients(){
       String query1;
        try{
            
            Statement sts = con.createStatement();
            query1= "SELECT ClientName FROM client;";
            ResultSet rst = sts.executeQuery(query1);

            while(rst.next()){
            cid.addItem(rst.getString(1));
            }
            
            
        }
        catch(Exception ex){
            System.out.println(ex+"as");
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        g1 = new javax.swing.ButtonGroup();
        g6 = new javax.swing.ButtonGroup();
        g2 = new javax.swing.ButtonGroup();
        g3 = new javax.swing.ButtonGroup();
        g4 = new javax.swing.ButtonGroup();
        g5 = new javax.swing.ButtonGroup();
        g7 = new javax.swing.ButtonGroup();
        g8 = new javax.swing.ButtonGroup();
        g9 = new javax.swing.ButtonGroup();
        g10 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        did = new javax.swing.JTextField();
        pid = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        feed = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel3 = new javax.swing.JPanel();
        dr1 = new javax.swing.JRadioButton();
        dr2 = new javax.swing.JRadioButton();
        dr3 = new javax.swing.JRadioButton();
        dr4 = new javax.swing.JRadioButton();
        lab1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        dr5 = new javax.swing.JRadioButton();
        dr6 = new javax.swing.JRadioButton();
        dr7 = new javax.swing.JRadioButton();
        dr8 = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        dr9 = new javax.swing.JRadioButton();
        dr10 = new javax.swing.JRadioButton();
        dr11 = new javax.swing.JRadioButton();
        dr12 = new javax.swing.JRadioButton();
        jLabel9 = new javax.swing.JLabel();
        dr13 = new javax.swing.JRadioButton();
        dr14 = new javax.swing.JRadioButton();
        dr15 = new javax.swing.JRadioButton();
        dr16 = new javax.swing.JRadioButton();
        jLabel10 = new javax.swing.JLabel();
        dr17 = new javax.swing.JRadioButton();
        dr18 = new javax.swing.JRadioButton();
        dr19 = new javax.swing.JRadioButton();
        dr20 = new javax.swing.JRadioButton();
        des = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jPanel4 = new javax.swing.JPanel();
        pm4 = new javax.swing.JRadioButton();
        pm3 = new javax.swing.JRadioButton();
        pm2 = new javax.swing.JRadioButton();
        pm1 = new javax.swing.JRadioButton();
        lab2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        pm5 = new javax.swing.JRadioButton();
        pm6 = new javax.swing.JRadioButton();
        pm7 = new javax.swing.JRadioButton();
        pm8 = new javax.swing.JRadioButton();
        jLabel8 = new javax.swing.JLabel();
        pm9 = new javax.swing.JRadioButton();
        pm10 = new javax.swing.JRadioButton();
        pm11 = new javax.swing.JRadioButton();
        pm12 = new javax.swing.JRadioButton();
        jLabel11 = new javax.swing.JLabel();
        pm13 = new javax.swing.JRadioButton();
        pm14 = new javax.swing.JRadioButton();
        pm15 = new javax.swing.JRadioButton();
        pm16 = new javax.swing.JRadioButton();
        pm17 = new javax.swing.JRadioButton();
        pm18 = new javax.swing.JRadioButton();
        pm19 = new javax.swing.JRadioButton();
        pm20 = new javax.swing.JRadioButton();
        jLabel12 = new javax.swing.JLabel();
        pmBtn = new javax.swing.JButton();
        jid1 = new javax.swing.JComboBox<>();
        dname = new javax.swing.JLabel();
        pname = new javax.swing.JLabel();
        cid = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Client Feedback");

        jPanel1.setBackground(new java.awt.Color(68, 108, 179));

        jScrollPane1.setBackground(new java.awt.Color(68, 108, 179));
        jScrollPane1.setForeground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(68, 108, 179));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));

        jLabel1.setBackground(new java.awt.Color(68, 108, 179));
        jLabel1.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Customer ID:");

        jLabel2.setBackground(new java.awt.Color(68, 108, 179));
        jLabel2.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("JobID:");

        jButton1.setBackground(new java.awt.Color(68, 108, 179));
        jButton1.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        jButton1.setText("Submit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel3.setBackground(new java.awt.Color(68, 108, 179));
        jLabel3.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Designer:");
        jLabel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel4.setBackground(new java.awt.Color(68, 108, 179));
        jLabel4.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Page Manager:");
        jLabel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        did.setFont(new java.awt.Font("Corbel", 0, 14)); // NOI18N
        did.setPreferredSize(new java.awt.Dimension(6, 25));
        did.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                didActionPerformed(evt);
            }
        });

        pid.setFont(new java.awt.Font("Corbel", 0, 14)); // NOI18N
        pid.setPreferredSize(new java.awt.Dimension(6, 25));
        pid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pidActionPerformed(evt);
            }
        });

        jLabel19.setBackground(new java.awt.Color(68, 108, 179));
        jLabel19.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Leave a comment or complaint to help us provide a better service next time. ");

        jLabel20.setBackground(new java.awt.Color(68, 108, 179));
        jLabel20.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("Feedback:");

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Tac-White.png"))); // NOI18N

        feed.setColumns(20);
        feed.setLineWrap(true);
        feed.setRows(5);
        jScrollPane4.setViewportView(feed);

        jPanel3.setBackground(new java.awt.Color(68, 108, 179));
        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        dr1.setBackground(new java.awt.Color(68, 108, 179));
        g1.add(dr1);
        dr1.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        dr1.setForeground(new java.awt.Color(255, 255, 255));
        dr1.setText("Need improvement");

        dr2.setBackground(new java.awt.Color(68, 108, 179));
        g1.add(dr2);
        dr2.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        dr2.setForeground(new java.awt.Color(255, 255, 255));
        dr2.setText("Satisfactory");

        dr3.setBackground(new java.awt.Color(68, 108, 179));
        g1.add(dr3);
        dr3.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        dr3.setForeground(new java.awt.Color(255, 255, 255));
        dr3.setText("Very good");

        dr4.setBackground(new java.awt.Color(68, 108, 179));
        g1.add(dr4);
        dr4.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        dr4.setForeground(new java.awt.Color(255, 255, 255));
        dr4.setText("Excellent");

        lab1.setBackground(new java.awt.Color(68, 108, 179));
        lab1.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        lab1.setForeground(new java.awt.Color(255, 255, 255));
        lab1.setText("Creativity, accuracy & artistic ability of designer");
        lab1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel5.setBackground(new java.awt.Color(68, 108, 179));
        jLabel5.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Technical expertise in the job done");
        jLabel5.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        dr5.setBackground(new java.awt.Color(68, 108, 179));
        g2.add(dr5);
        dr5.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        dr5.setForeground(new java.awt.Color(255, 255, 255));
        dr5.setText("Need improvement");

        dr6.setBackground(new java.awt.Color(68, 108, 179));
        g2.add(dr6);
        dr6.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        dr6.setForeground(new java.awt.Color(255, 255, 255));
        dr6.setText("Satisfactory");
        dr6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dr6ActionPerformed(evt);
            }
        });

        dr7.setBackground(new java.awt.Color(68, 108, 179));
        g2.add(dr7);
        dr7.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        dr7.setForeground(new java.awt.Color(255, 255, 255));
        dr7.setText("Very good");

        dr8.setBackground(new java.awt.Color(68, 108, 179));
        g2.add(dr8);
        dr8.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        dr8.setForeground(new java.awt.Color(255, 255, 255));
        dr8.setText("Excellent");
        dr8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dr8ActionPerformed(evt);
            }
        });

        jLabel6.setBackground(new java.awt.Color(68, 108, 179));
        jLabel6.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Effectiveness in communication");
        jLabel6.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        dr9.setBackground(new java.awt.Color(68, 108, 179));
        g3.add(dr9);
        dr9.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        dr9.setForeground(new java.awt.Color(255, 255, 255));
        dr9.setText("Need improvement");

        dr10.setBackground(new java.awt.Color(68, 108, 179));
        g3.add(dr10);
        dr10.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        dr10.setForeground(new java.awt.Color(255, 255, 255));
        dr10.setText("Satisfactory");
        dr10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dr10ActionPerformed(evt);
            }
        });

        dr11.setBackground(new java.awt.Color(68, 108, 179));
        g3.add(dr11);
        dr11.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        dr11.setForeground(new java.awt.Color(255, 255, 255));
        dr11.setText("Very good");

        dr12.setBackground(new java.awt.Color(68, 108, 179));
        g3.add(dr12);
        dr12.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        dr12.setForeground(new java.awt.Color(255, 255, 255));
        dr12.setText("Excellent");
        dr12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dr12ActionPerformed(evt);
            }
        });

        jLabel9.setBackground(new java.awt.Color(68, 108, 179));
        jLabel9.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Overall performance and reliability of the designer");
        jLabel9.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        dr13.setBackground(new java.awt.Color(68, 108, 179));
        g4.add(dr13);
        dr13.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        dr13.setForeground(new java.awt.Color(255, 255, 255));
        dr13.setText("Need improvement");

        dr14.setBackground(new java.awt.Color(68, 108, 179));
        g4.add(dr14);
        dr14.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        dr14.setForeground(new java.awt.Color(255, 255, 255));
        dr14.setText("Satisfactory");
        dr14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dr14ActionPerformed(evt);
            }
        });

        dr15.setBackground(new java.awt.Color(68, 108, 179));
        g4.add(dr15);
        dr15.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        dr15.setForeground(new java.awt.Color(255, 255, 255));
        dr15.setText("Very good");

        dr16.setBackground(new java.awt.Color(68, 108, 179));
        g4.add(dr16);
        dr16.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        dr16.setForeground(new java.awt.Color(255, 255, 255));
        dr16.setText("Excellent");
        dr16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dr16ActionPerformed(evt);
            }
        });

        jLabel10.setBackground(new java.awt.Color(68, 108, 179));
        jLabel10.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("His/Her ability to handle tight deadlines & pressure");
        jLabel10.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        dr17.setBackground(new java.awt.Color(68, 108, 179));
        g5.add(dr17);
        dr17.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        dr17.setForeground(new java.awt.Color(255, 255, 255));
        dr17.setText("Need improvement");

        dr18.setBackground(new java.awt.Color(68, 108, 179));
        g5.add(dr18);
        dr18.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        dr18.setForeground(new java.awt.Color(255, 255, 255));
        dr18.setText("Satisfactory");
        dr18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dr18ActionPerformed(evt);
            }
        });

        dr19.setBackground(new java.awt.Color(68, 108, 179));
        g5.add(dr19);
        dr19.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        dr19.setForeground(new java.awt.Color(255, 255, 255));
        dr19.setText("Very good");

        dr20.setBackground(new java.awt.Color(68, 108, 179));
        g5.add(dr20);
        dr20.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        dr20.setForeground(new java.awt.Color(255, 255, 255));
        dr20.setText("Excellent");
        dr20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dr20ActionPerformed(evt);
            }
        });

        des.setBackground(new java.awt.Color(68, 108, 179));
        des.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        des.setText("Rate");
        des.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                desActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(36, 36, 36)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(dr4)
                                    .addComponent(dr3)
                                    .addComponent(dr2)
                                    .addComponent(dr1)))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(43, 43, 43)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(dr6)
                                    .addComponent(dr5)
                                    .addComponent(dr7)
                                    .addComponent(dr8))))
                        .addGap(220, 220, 220))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lab1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGap(25, 25, 25)
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(dr14)
                                            .addComponent(dr13)
                                            .addComponent(dr15)
                                            .addComponent(dr16)))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGap(23, 23, 23)
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(dr18)
                                            .addComponent(dr17)
                                            .addComponent(dr19)
                                            .addGroup(jPanel3Layout.createSequentialGroup()
                                                .addComponent(dr20)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(des)))))
                                .addGap(23, 23, 23)))))
                .addContainerGap())
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dr10)
                    .addComponent(dr9)
                    .addComponent(dr11)
                    .addComponent(dr12))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(lab1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(dr1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(dr2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(dr3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dr4)
                .addGap(14, 14, 14)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(dr5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(dr6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(dr7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(dr8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(dr9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(dr10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(dr11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(dr12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(dr13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(dr14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(dr15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(dr16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(dr17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(dr18)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(dr19)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(dr20)
                        .addContainerGap(30, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(des)
                        .addContainerGap())))
        );

        jScrollPane2.setViewportView(jPanel3);

        jPanel4.setBackground(new java.awt.Color(68, 108, 179));
        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        pm4.setBackground(new java.awt.Color(68, 108, 179));
        g6.add(pm4);
        pm4.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        pm4.setForeground(new java.awt.Color(255, 255, 255));
        pm4.setText("Excellent");

        pm3.setBackground(new java.awt.Color(68, 108, 179));
        g6.add(pm3);
        pm3.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        pm3.setForeground(new java.awt.Color(255, 255, 255));
        pm3.setText("Very good");
        pm3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pm3ActionPerformed(evt);
            }
        });

        pm2.setBackground(new java.awt.Color(68, 108, 179));
        g6.add(pm2);
        pm2.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        pm2.setForeground(new java.awt.Color(255, 255, 255));
        pm2.setText("Satisfactory");

        pm1.setBackground(new java.awt.Color(68, 108, 179));
        g6.add(pm1);
        pm1.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        pm1.setForeground(new java.awt.Color(255, 255, 255));
        pm1.setText("Need improvement");
        pm1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pm1ActionPerformed(evt);
            }
        });

        lab2.setBackground(new java.awt.Color(68, 108, 179));
        lab2.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        lab2.setForeground(new java.awt.Color(255, 255, 255));
        lab2.setText("Creativeness, accuracy and attractiveness of work done");
        lab2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel7.setBackground(new java.awt.Color(68, 108, 179));
        jLabel7.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Page manager's talent in understanding & identifying requirements");
        jLabel7.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        pm5.setBackground(new java.awt.Color(68, 108, 179));
        g7.add(pm5);
        pm5.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        pm5.setForeground(new java.awt.Color(255, 255, 255));
        pm5.setText("Need improvement");

        pm6.setBackground(new java.awt.Color(68, 108, 179));
        g7.add(pm6);
        pm6.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        pm6.setForeground(new java.awt.Color(255, 255, 255));
        pm6.setText("Satisfactory");
        pm6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pm6ActionPerformed(evt);
            }
        });

        pm7.setBackground(new java.awt.Color(68, 108, 179));
        g7.add(pm7);
        pm7.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        pm7.setForeground(new java.awt.Color(255, 255, 255));
        pm7.setText("Very good");

        pm8.setBackground(new java.awt.Color(68, 108, 179));
        g7.add(pm8);
        pm8.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        pm8.setForeground(new java.awt.Color(255, 255, 255));
        pm8.setText("Excellent");

        jLabel8.setBackground(new java.awt.Color(68, 108, 179));
        jLabel8.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Page manager's flexibility to Your changing requirements");
        jLabel8.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        pm9.setBackground(new java.awt.Color(68, 108, 179));
        g8.add(pm9);
        pm9.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        pm9.setForeground(new java.awt.Color(255, 255, 255));
        pm9.setText("Need improvement");

        pm10.setBackground(new java.awt.Color(68, 108, 179));
        g8.add(pm10);
        pm10.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        pm10.setForeground(new java.awt.Color(255, 255, 255));
        pm10.setText("Satisfactory");
        pm10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pm10ActionPerformed(evt);
            }
        });

        pm11.setBackground(new java.awt.Color(68, 108, 179));
        g8.add(pm11);
        pm11.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        pm11.setForeground(new java.awt.Color(255, 255, 255));
        pm11.setText("Very good");

        pm12.setBackground(new java.awt.Color(68, 108, 179));
        g8.add(pm12);
        pm12.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        pm12.setForeground(new java.awt.Color(255, 255, 255));
        pm12.setText("Excellent");

        jLabel11.setBackground(new java.awt.Color(68, 108, 179));
        jLabel11.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Knowledge & expertise demonstrated on the job");
        jLabel11.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        pm13.setBackground(new java.awt.Color(68, 108, 179));
        g9.add(pm13);
        pm13.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        pm13.setForeground(new java.awt.Color(255, 255, 255));
        pm13.setText("Need improvement");

        pm14.setBackground(new java.awt.Color(68, 108, 179));
        g9.add(pm14);
        pm14.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        pm14.setForeground(new java.awt.Color(255, 255, 255));
        pm14.setText("Satisfactory");
        pm14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pm14ActionPerformed(evt);
            }
        });

        pm15.setBackground(new java.awt.Color(68, 108, 179));
        g9.add(pm15);
        pm15.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        pm15.setForeground(new java.awt.Color(255, 255, 255));
        pm15.setText("Very good");

        pm16.setBackground(new java.awt.Color(68, 108, 179));
        g9.add(pm16);
        pm16.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        pm16.setForeground(new java.awt.Color(255, 255, 255));
        pm16.setText("Excellent");

        pm17.setBackground(new java.awt.Color(68, 108, 179));
        g10.add(pm17);
        pm17.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        pm17.setForeground(new java.awt.Color(255, 255, 255));
        pm17.setText("Excellent");

        pm18.setBackground(new java.awt.Color(68, 108, 179));
        g10.add(pm18);
        pm18.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        pm18.setForeground(new java.awt.Color(255, 255, 255));
        pm18.setText("Very good");

        pm19.setBackground(new java.awt.Color(68, 108, 179));
        g10.add(pm19);
        pm19.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        pm19.setForeground(new java.awt.Color(255, 255, 255));
        pm19.setText("Satisfactory");
        pm19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pm19ActionPerformed(evt);
            }
        });

        pm20.setBackground(new java.awt.Color(68, 108, 179));
        g10.add(pm20);
        pm20.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        pm20.setForeground(new java.awt.Color(255, 255, 255));
        pm20.setText("Need improvement");

        jLabel12.setBackground(new java.awt.Color(68, 108, 179));
        jLabel12.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Overall performance & reliability of the designer");
        jLabel12.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        pmBtn.setBackground(new java.awt.Color(68, 108, 179));
        pmBtn.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        pmBtn.setText("Rate");
        pmBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pmBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pm12)
                    .addComponent(pm11)
                    .addComponent(pm10)
                    .addComponent(pm9))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(35, 35, 35)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(pm4)
                                    .addComponent(pm1)
                                    .addComponent(pm3)
                                    .addComponent(pm2)))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(pm8)
                                    .addComponent(pm7)
                                    .addComponent(pm6)
                                    .addComponent(pm5))))
                        .addGap(0, 239, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lab2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(pm16)
                                    .addComponent(pm15)
                                    .addComponent(pm14)
                                    .addComponent(pm13)
                                    .addComponent(pm18)
                                    .addComponent(pm19)
                                    .addComponent(pm20)
                                    .addComponent(pm17))
                                .addGap(235, 235, 235)))))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pmBtn)
                .addGap(27, 27, 27))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(lab2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pm1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pm2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pm3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pm4)
                .addGap(16, 16, 16)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pm5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pm6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pm7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pm8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pm9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pm10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pm11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pm12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pm13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pm14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pm15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pm16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pm20)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pm19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pm18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pm17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pmBtn)
                .addContainerGap())
        );

        jScrollPane3.setViewportView(jPanel4);

        jid1.setBackground(new java.awt.Color(68, 108, 179));
        jid1.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        jid1.setMaximumRowCount(10);
        jid1.setPreferredSize(new java.awt.Dimension(65, 50));
        jid1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jid1MouseClicked(evt);
            }
        });
        jid1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jid1ActionPerformed(evt);
            }
        });

        cid.setBackground(new java.awt.Color(68, 108, 179));
        cid.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        cid.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select" }));
        cid.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cidMouseClicked(evt);
            }
        });
        cid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cidActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 464, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 766, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(did, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(dname, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 445, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 455, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(pid, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(pname, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(99, 99, 99)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cid, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jid1, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(23, 23, 23))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jid1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(cid, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(pid, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(did, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(dname, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pname, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 455, Short.MAX_VALUE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );

        jScrollPane1.setViewportView(jPanel2);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 980, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 578, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void pidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pidActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
       
        int CID=0;
        String Cus = cid.getSelectedItem().toString();
        String PID = pid.getText();
        String JID = jid1.getSelectedItem().toString();
        String DID = did.getText();
        String FEED = feed.getText();
        int dm= sum; 
        int pm= psum; 
        
        try{
            String qu="SELECT clientID FROM client WHERE ClientName='"+Cus+"';";
            PreparedStatement pstt = con.prepareStatement(qu);
            ResultSet rslt= pstt.executeQuery();
            
            while(rslt.next()){
            CID=rslt.getInt(1);
            }
        
         System.out.println();
        SimpleDateFormat df = new SimpleDateFormat("yyyy-MM-dd");
        String formatted = df.format(new Date());
        
        Date currentDate = new Date();
        
        
         Calendar c = Calendar.getInstance(); //convert date to calander date
         c.setTime(currentDate); 
         c.add(Calendar.DATE, 3 ); //add 3 days reply deadline
         Date dead = c.getTime(); //convert calander to date
         String DEAD =df.format(dead); 
         
         if(cid.getSelectedIndex()!=0){
             if(jid1.getSelectedIndex()!=0){
	   if(!PID.isEmpty()){
	       if(!DID.isEmpty()){
	           if(pm!=0){
		 if(dm!=0){
		     if(!FEED.isEmpty()){
		         String sql;
		            try{
			  sql="INSERT INTO feedback (custID,jobID,pageManagerID,designerID,fbDate,designerMarks,pageManagerMarks,comment,replyDeadline) VALUES ('" +CID+ "', '"+JID+"', '" +PID+ "', '" +DID+ "', '" +formatted+ "', '" +dm+ "', '" +pm+ "', '" +FEED+ "', '" +DEAD+ "');"  ;
			  pst = con.prepareStatement(sql);
			  pst.execute();

			  JOptionPane.showMessageDialog(null,"Thankyou for your Time! "
			      + "\n Have a nice Day!");
			  Home h1=new  Home();
			  h1.setVisible(true);
			  this.dispose();

		            } catch(SQLException ex){
			  System.out.println(ex);
			  JOptionPane.showMessageDialog(null,"Feedback for this job has already been taken!");
			  Home h2=new  Home();
			  h2.setVisible(true);
			  this.dispose();
		            }
		    } else{JOptionPane.showMessageDialog(null,"Please type in your feedback!");}
		 }else{JOptionPane.showMessageDialog(null,"Please rate the Designer!");}
	           } else{JOptionPane.showMessageDialog(null,"Please rate the page Manager!");}
	       } else{JOptionPane.showMessageDialog(null,"Enter DesignerID");}
	  } else{JOptionPane.showMessageDialog(null,"Select Page ManagerID");}
            } else{JOptionPane.showMessageDialog(null,"Select JobID");}
         } else{
             pid.setText("");
             did.setText("");
             JOptionPane.showMessageDialog(null,"Enter CustomerID");}
         } catch(Exception ex){
            System.out.println(ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void didActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_didActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_didActionPerformed

    private void pm3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pm3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pm3ActionPerformed

    private void dr6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dr6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dr6ActionPerformed

    private void dr8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dr8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dr8ActionPerformed

    private void dr10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dr10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dr10ActionPerformed

    private void dr12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dr12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dr12ActionPerformed

    private void pm6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pm6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pm6ActionPerformed

    private void pm10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pm10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pm10ActionPerformed

    private void dr14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dr14ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dr14ActionPerformed

    private void dr16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dr16ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dr16ActionPerformed

    private void dr18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dr18ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dr18ActionPerformed

    private void dr20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dr20ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dr20ActionPerformed

    private void pm14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pm14ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pm14ActionPerformed

    private void pm19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pm19ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pm19ActionPerformed

    private void pm1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pm1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pm1ActionPerformed

    private void desActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_desActionPerformed
        // TODO add your handling code here:
       
        sum=0; 
       if(dr1.isSelected())
            {sum+=1;}
        else if(dr2.isSelected())
            {sum+=2;}
        else if(dr3.isSelected())
            {sum+=3;}
        else if(dr4.isSelected())
            {sum+=4;}
       {
	   if(dr5.isSelected())
	       {sum+=1;}
	   else if(dr6.isSelected())
	       {sum+=2;}
	   else if(dr7.isSelected())
	       {sum+=3;}
	   else if(dr8.isSelected())
	       {sum+=4;}
	  { 
	      if(dr9.isSelected())
	          {sum+=1;}
	      else if(dr10.isSelected())
	          {sum+=2;}
	      else if(dr11.isSelected())
	          {sum+=3;}
	      else if(dr12.isSelected())
	          {sum+=4;}
	         {
		if(dr13.isSelected())
		    {sum+=1;}
		else if(dr14.isSelected())
		    {sum+=2;}
		else if(dr15.isSelected())
		    {sum+=3;}
		else if(dr16.isSelected())
		    {sum+=4;}
		    {
		        if(dr17.isSelected())
		            {sum+=1;}
		        else if(dr18.isSelected())
		            {sum+=2;}
		        else if(dr19.isSelected())
		            {sum+=3;}
		        else if(dr20.isSelected())
		            {sum+=4;}
                    }}}}
       
       if(g1.getSelection()==null||g2.getSelection()==null||g3.getSelection()==null||g4.getSelection()==null||g5.getSelection()==null)
            {
	     JOptionPane.showMessageDialog(null,"Please answer all questions!");
            }
       
    }//GEN-LAST:event_desActionPerformed

    private void pmBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pmBtnActionPerformed
        // TODO add your handling code here:
       psum=0;
        if(pm1.isSelected())
            {psum+=1;}
        else if(pm2.isSelected())
            {psum+=2;}
        else if(pm3.isSelected())
            {psum+=3;}
        else if(pm4.isSelected())
            {psum+=4;}
       {
	   if(pm5.isSelected())
	       {psum+=1;}
	   else if(pm6.isSelected())
	       {psum+=2;}
	   else if(pm7.isSelected())
	       {psum+=3;}
	   else if(pm8.isSelected())
	       {psum+=4;}
	  { 
	      if(pm9.isSelected())
	          {psum+=1;}
	      else if(pm10.isSelected())
	          {psum+=2;}
	      else if(pm11.isSelected())
	          {psum+=3;}
	      else if(pm12.isSelected())
	          {psum+=4;}
	      {
	          if(pm13.isSelected())
		{psum+=1;}
	          else if(pm14.isSelected())
		{psum+=2;}
	          else if(pm15.isSelected())
		{psum+=3;}
	          else if(pm16.isSelected())
		{psum+=4;}
	          {
		 if(pm17.isSelected())
		    {psum+=1;}
		else if(pm18.isSelected())
		    {psum+=2;}
		else if(pm19.isSelected())
		    {psum+=3;}
		else if(pm20.isSelected())
		    {psum+=4;}
                  }}}}
       
       if(g6.getSelection()==null||g7.getSelection()==null||g8.getSelection()==null||g9.getSelection()==null||g10.getSelection()==null)
            {
	     JOptionPane.showMessageDialog(null,"Please answer all questions!");
            }
    }//GEN-LAST:event_pmBtnActionPerformed

    private void jid1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jid1ActionPerformed
        // TODO add your handling code here:
        //jobs();
        String job=jid1.getSelectedItem().toString();
            
            String query2;
            try{
	  Statement sts1 = con.createStatement();
	  query2= "SELECT c.desID, c.pgID FROM client c, jobtac j WHERE c.ClientName=j.client AND j.TACID='"+job+ "' ";
	  ResultSet rst1 = sts1.executeQuery(query2);
	  
	  while(rst1.next()){
                did.setText(rst1.getString(1));
	  pid.setText(rst1.getString(2));
	  }
	  
            } catch(Exception ex){
            System.out.println(ex+"sa");
        }
    }//GEN-LAST:event_jid1ActionPerformed

    private void jid1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jid1MouseClicked
        // TODO add your handling code here:
    
    }//GEN-LAST:event_jid1MouseClicked

    private void cidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cidActionPerformed
        // TODO add your handling code here:
        try{
           // clear();
            try{
	  jobs();
            } catch(Exception ex){
	  System.out.println(ex+"sw");
            }
        }catch(Exception ex){
	  System.out.println(ex+"saS");
            }
        
    }//GEN-LAST:event_cidActionPerformed

    private void cidMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cidMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_cidMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
	  if ("Nimbus".equals(info.getName())) {
	      javax.swing.UIManager.setLookAndFeel(info.getClassName());
	      break;
	  }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(clientFeedback.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(clientFeedback.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(clientFeedback.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(clientFeedback.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
	  new clientFeedback().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cid;
    private javax.swing.JButton des;
    private javax.swing.JTextField did;
    private javax.swing.JLabel dname;
    private javax.swing.JRadioButton dr1;
    private javax.swing.JRadioButton dr10;
    private javax.swing.JRadioButton dr11;
    private javax.swing.JRadioButton dr12;
    private javax.swing.JRadioButton dr13;
    private javax.swing.JRadioButton dr14;
    private javax.swing.JRadioButton dr15;
    private javax.swing.JRadioButton dr16;
    private javax.swing.JRadioButton dr17;
    private javax.swing.JRadioButton dr18;
    private javax.swing.JRadioButton dr19;
    private javax.swing.JRadioButton dr2;
    private javax.swing.JRadioButton dr20;
    private javax.swing.JRadioButton dr3;
    private javax.swing.JRadioButton dr4;
    private javax.swing.JRadioButton dr5;
    private javax.swing.JRadioButton dr6;
    private javax.swing.JRadioButton dr7;
    private javax.swing.JRadioButton dr8;
    private javax.swing.JRadioButton dr9;
    private javax.swing.JTextArea feed;
    private javax.swing.ButtonGroup g1;
    private javax.swing.ButtonGroup g10;
    private javax.swing.ButtonGroup g2;
    private javax.swing.ButtonGroup g3;
    private javax.swing.ButtonGroup g4;
    private javax.swing.ButtonGroup g5;
    private javax.swing.ButtonGroup g6;
    private javax.swing.ButtonGroup g7;
    private javax.swing.ButtonGroup g8;
    private javax.swing.ButtonGroup g9;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JComboBox<String> jid1;
    private javax.swing.JLabel lab1;
    private javax.swing.JLabel lab2;
    private javax.swing.JTextField pid;
    private javax.swing.JRadioButton pm1;
    private javax.swing.JRadioButton pm10;
    private javax.swing.JRadioButton pm11;
    private javax.swing.JRadioButton pm12;
    private javax.swing.JRadioButton pm13;
    private javax.swing.JRadioButton pm14;
    private javax.swing.JRadioButton pm15;
    private javax.swing.JRadioButton pm16;
    private javax.swing.JRadioButton pm17;
    private javax.swing.JRadioButton pm18;
    private javax.swing.JRadioButton pm19;
    private javax.swing.JRadioButton pm2;
    private javax.swing.JRadioButton pm20;
    private javax.swing.JRadioButton pm3;
    private javax.swing.JRadioButton pm4;
    private javax.swing.JRadioButton pm5;
    private javax.swing.JRadioButton pm6;
    private javax.swing.JRadioButton pm7;
    private javax.swing.JRadioButton pm8;
    private javax.swing.JRadioButton pm9;
    private javax.swing.JButton pmBtn;
    private javax.swing.JLabel pname;
    // End of variables declaration//GEN-END:variables
}
