/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

import java.awt.Color;

/**
 *
 * @author Shadow Walker
 */
public class Employee extends javax.swing.JFrame {

    /**
     * Creates new form Employee
     */
    public Employee() {
        initComponents();
        
        AddEmployee1 add =new AddEmployee1();
        jDesktopPane1.removeAll();
        jDesktopPane1.add(add).setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        addEmp = new javax.swing.JPanel();
        add = new javax.swing.JLabel();
        updEmp = new javax.swing.JPanel();
        up = new javax.swing.JLabel();
        gensal = new javax.swing.JPanel();
        gen = new javax.swing.JLabel();
        salMng1 = new javax.swing.JPanel();
        sal = new javax.swing.JLabel();
        report = new javax.swing.JPanel();
        rep = new javax.swing.JLabel();
        jDesktopPane1 = new javax.swing.JDesktopPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Employee and Salary Management");
        setMaximumSize(new java.awt.Dimension(1000, 700));
        setMinimumSize(new java.awt.Dimension(1000, 700));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(68, 108, 179));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        jButton1.setBackground(new java.awt.Color(68, 108, 179));
        jButton1.setFont(new java.awt.Font("Corbel", 0, 36)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Tac-White.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(30, 30, 140, 60);
        jPanel1.add(jSeparator1);
        jSeparator1.setBounds(0, 112, 210, 20);

        addEmp.setBackground(new java.awt.Color(68, 108, 179));
        addEmp.setMinimumSize(new java.awt.Dimension(200, 60));
        addEmp.setPreferredSize(new java.awt.Dimension(200, 60));
        addEmp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                addEmpMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                addEmpMouseExited(evt);
            }
        });

        add.setBackground(new java.awt.Color(68, 108, 179));
        add.setFont(new java.awt.Font("Corbel", 0, 18)); // NOI18N
        add.setForeground(new java.awt.Color(255, 255, 255));
        add.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Add User Male_45px.png"))); // NOI18N
        add.setText(" Add Employee");
        add.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                addMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                addMouseExited(evt);
            }
        });

        javax.swing.GroupLayout addEmpLayout = new javax.swing.GroupLayout(addEmp);
        addEmp.setLayout(addEmpLayout);
        addEmpLayout.setHorizontalGroup(
            addEmpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addEmpLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(add)
                .addContainerGap(26, Short.MAX_VALUE))
        );
        addEmpLayout.setVerticalGroup(
            addEmpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(add, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );

        jPanel1.add(addEmp);
        addEmp.setBounds(0, 160, 200, 60);

        updEmp.setBackground(new java.awt.Color(68, 108, 179));
        updEmp.setMinimumSize(new java.awt.Dimension(200, 60));
        updEmp.setPreferredSize(new java.awt.Dimension(200, 60));
        updEmp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                updEmpMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                updEmpMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                updEmpMouseExited(evt);
            }
        });

        up.setBackground(new java.awt.Color(68, 108, 179));
        up.setFont(new java.awt.Font("Corbel", 0, 18)); // NOI18N
        up.setForeground(new java.awt.Color(255, 255, 255));
        up.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Refresh_30px.png"))); // NOI18N
        up.setText(" Update Employee");
        up.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                upMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                upMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                upMouseExited(evt);
            }
        });

        javax.swing.GroupLayout updEmpLayout = new javax.swing.GroupLayout(updEmp);
        updEmp.setLayout(updEmpLayout);
        updEmpLayout.setHorizontalGroup(
            updEmpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, updEmpLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(up, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE))
        );
        updEmpLayout.setVerticalGroup(
            updEmpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(updEmpLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(up, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.add(updEmp);
        updEmp.setBounds(0, 250, 200, 60);

        gensal.setBackground(new java.awt.Color(68, 108, 179));
        gensal.setMinimumSize(new java.awt.Dimension(100, 60));
        gensal.setPreferredSize(new java.awt.Dimension(200, 60));
        gensal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                gensalMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                gensalMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                gensalMouseExited(evt);
            }
        });

        gen.setFont(new java.awt.Font("Corbel", 0, 18)); // NOI18N
        gen.setForeground(new java.awt.Color(255, 255, 255));
        gen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/salary slip 30x.png"))); // NOI18N
        gen.setText("Generate Salary Slip");
        gen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                genMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                genMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                genMouseExited(evt);
            }
        });

        javax.swing.GroupLayout gensalLayout = new javax.swing.GroupLayout(gensal);
        gensal.setLayout(gensalLayout);
        gensalLayout.setHorizontalGroup(
            gensalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(gensalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(gen)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        gensalLayout.setVerticalGroup(
            gensalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(gensalLayout.createSequentialGroup()
                .addComponent(gen, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 21, Short.MAX_VALUE))
        );

        jPanel1.add(gensal);
        gensal.setBounds(0, 420, 200, 50);

        salMng1.setBackground(new java.awt.Color(68, 108, 179));
        salMng1.setMinimumSize(new java.awt.Dimension(200, 60));
        salMng1.setPreferredSize(new java.awt.Dimension(200, 60));
        salMng1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                salMng1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                salMng1MouseExited(evt);
            }
        });

        sal.setFont(new java.awt.Font("Corbel", 0, 18)); // NOI18N
        sal.setForeground(new java.awt.Color(255, 255, 255));
        sal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Money Bag_30px.png"))); // NOI18N
        sal.setText(" Salary Management");
        sal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                salMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                salMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                salMouseExited(evt);
            }
        });

        javax.swing.GroupLayout salMng1Layout = new javax.swing.GroupLayout(salMng1);
        salMng1.setLayout(salMng1Layout);
        salMng1Layout.setHorizontalGroup(
            salMng1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(salMng1Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(sal)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        salMng1Layout.setVerticalGroup(
            salMng1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, salMng1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(sal, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.add(salMng1);
        salMng1.setBounds(0, 333, 200, 60);

        report.setBackground(new java.awt.Color(68, 108, 179));
        report.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                reportMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                reportMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                reportMouseExited(evt);
            }
        });

        rep.setFont(new java.awt.Font("Corbel", 0, 18)); // NOI18N
        rep.setForeground(new java.awt.Color(255, 255, 255));
        rep.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/High Connection_30px.png"))); // NOI18N
        rep.setText("       Reports");
        rep.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                repMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                repMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                repMouseExited(evt);
            }
        });

        javax.swing.GroupLayout reportLayout = new javax.swing.GroupLayout(report);
        report.setLayout(reportLayout);
        reportLayout.setHorizontalGroup(
            reportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
            .addGroup(reportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, reportLayout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(rep, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(19, Short.MAX_VALUE)))
        );
        reportLayout.setVerticalGroup(
            reportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 52, Short.MAX_VALUE)
            .addGroup(reportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(reportLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(rep, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        jPanel1.add(report);
        report.setBounds(0, 490, 200, 50);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 198, 700));

        jDesktopPane1.setMaximumSize(new java.awt.Dimension(796, 700));
        jDesktopPane1.setMinimumSize(new java.awt.Dimension(796, 700));

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 796, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 700, Short.MAX_VALUE)
        );

        getContentPane().add(jDesktopPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 0, 790, 700));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void gensalMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gensalMouseExited

        gensal.setBackground(Color.decode("#446cb3"));

        // TODO add your handling code here:
    }//GEN-LAST:event_gensalMouseExited

    private void gensalMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gensalMouseEntered

        gensal.setBackground(Color.decode("#4456b2"));

        // TODO add your handling code here:
    }//GEN-LAST:event_gensalMouseEntered

    private void salMng1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_salMng1MouseExited

        salMng1.setBackground(Color.decode("#446cb3"));

        // TODO add your handling code here:
    }//GEN-LAST:event_salMng1MouseExited

    private void salMng1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_salMng1MouseEntered

        salMng1.setBackground(Color.decode("#4456b2"));

        // TODO add your handling code here:
    }//GEN-LAST:event_salMng1MouseEntered

    private void updEmpMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updEmpMouseExited

        updEmp.setBackground(Color.decode("#446cb3"));
        // TODO add your handling code here:
    }//GEN-LAST:event_updEmpMouseExited

    private void updEmpMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updEmpMouseEntered

        updEmp.setBackground(Color.decode("#4456b2"));
        // TODO add your handling code here:
    }//GEN-LAST:event_updEmpMouseEntered

    private void addEmpMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addEmpMouseExited

        addEmp.setBackground(Color.decode("#446cb3"));

        // TODO add your handling code here:
    }//GEN-LAST:event_addEmpMouseExited

    private void addEmpMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addEmpMouseEntered

        addEmp.setBackground(Color.decode("#4456b2"));

        // TODO add your handling code here:
    }//GEN-LAST:event_addEmpMouseEntered

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Home h1 =new Home();
        h1.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void addMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addMouseClicked
        // TODO add your handling code here:
         AddEmployee1 add =new AddEmployee1();
        jDesktopPane1.removeAll();
        jDesktopPane1.add(add).setVisible(true);
        
        
    }//GEN-LAST:event_addMouseClicked

    private void upMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_upMouseClicked
        // TODO add your handling code here:
        
        UpdateEmployee1 add =new UpdateEmployee1();
        jDesktopPane1.removeAll();
        jDesktopPane1.add(add).setVisible(true);
    }//GEN-LAST:event_upMouseClicked

    private void salMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_salMouseClicked
        // TODO add your handling code here:
        
        SalaryManagement1 add =new SalaryManagement1();
        jDesktopPane1.removeAll();
        jDesktopPane1.add(add).setVisible(true);
    }//GEN-LAST:event_salMouseClicked

    private void genMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_genMouseClicked
        // TODO add your handling code here:
        
        GenerateSalarySlip add =new GenerateSalarySlip();
        jDesktopPane1.removeAll();
        jDesktopPane1.add(add).setVisible(true);
    }//GEN-LAST:event_genMouseClicked

    private void upMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_upMouseEntered
        // TODO add your handling code here:
        
        updEmp.setBackground(Color.decode("#4456b2"));
        
    }//GEN-LAST:event_upMouseEntered

    private void addMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addMouseEntered
        // TODO add your handling code here:
        
        addEmp.setBackground(Color.decode("#4456b2"));
    }//GEN-LAST:event_addMouseEntered

    private void salMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_salMouseEntered
        // TODO add your handling code here:
        
    salMng1.setBackground(Color.decode("#4456b2"));
    }//GEN-LAST:event_salMouseEntered

    private void genMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_genMouseEntered
        // TODO add your handling code here:
        gen.setBackground(Color.decode("#4456b2"));
    }//GEN-LAST:event_genMouseEntered

    private void addMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addMouseExited
        // TODO add your handling code here:
        
        addEmp.setBackground(Color.decode("#446cb3"));
    }//GEN-LAST:event_addMouseExited

    private void genMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_genMouseExited
        // TODO add your handling code here:
        gen.setBackground(Color.decode("#446cb3"));
    }//GEN-LAST:event_genMouseExited

    private void salMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_salMouseExited
        // TODO add your handling code here:
         salMng1.setBackground(Color.decode("#446cb3"));
    }//GEN-LAST:event_salMouseExited

    private void upMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_upMouseExited
        // TODO add your handling code here:
      up.setBackground(Color.decode("#446cb3"));
        
    }//GEN-LAST:event_upMouseExited

    private void updEmpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updEmpMouseClicked
        // TODO add your handling code here:
         UpdateEmployee1 add =new UpdateEmployee1();
        jDesktopPane1.removeAll();
        jDesktopPane1.add(add).setVisible(true);
    }//GEN-LAST:event_updEmpMouseClicked

    private void repMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_repMouseClicked
        // TODO add your handling code here:
        EmployeeReports ad1 =new EmployeeReports();
        jDesktopPane1.removeAll();
        jDesktopPane1.add(ad1).setVisible(true);
    }//GEN-LAST:event_repMouseClicked

    private void repMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_repMouseEntered
        // TODO add your handling code here:
         rep.setBackground(Color.decode("#4456b2"));
    }//GEN-LAST:event_repMouseEntered

    private void repMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_repMouseExited
        // TODO add your handling code here:
        rep.setBackground(Color.decode("#446cb3"));
    }//GEN-LAST:event_repMouseExited

    private void gensalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gensalMouseClicked
        // TODO add your handling code here:
        GenerateSalarySlip add3 =new GenerateSalarySlip();
        jDesktopPane1.removeAll();
        jDesktopPane1.add(add3).setVisible(true);
    }//GEN-LAST:event_gensalMouseClicked

    private void reportMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reportMouseClicked
        // TODO add your handling code here:
        EmployeeReports add4 =new EmployeeReports();
        jDesktopPane1.removeAll();
        jDesktopPane1.add(add4).setVisible(true);
    }//GEN-LAST:event_reportMouseClicked

    private void reportMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reportMouseEntered
        // TODO add your handling code here:
         report.setBackground(Color.decode("#4456b2"));
    }//GEN-LAST:event_reportMouseEntered

    private void reportMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reportMouseExited
        // TODO add your handling code here:
        report.setBackground(Color.decode("#446cb3"));
    }//GEN-LAST:event_reportMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Employee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Employee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Employee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Employee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Employee().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel add;
    private javax.swing.JPanel addEmp;
    private javax.swing.JLabel gen;
    private javax.swing.JPanel gensal;
    private javax.swing.JButton jButton1;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel rep;
    private javax.swing.JPanel report;
    private javax.swing.JLabel sal;
    private javax.swing.JPanel salMng1;
    private javax.swing.JLabel up;
    private javax.swing.JPanel updEmp;
    // End of variables declaration//GEN-END:variables
}
