/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

import ConnectDatabase.DatabaseConnection;

import java.awt.Dimension;
import com.itextpdf.text.Document;
import com.itextpdf.text.FontFactory;
import com.itextpdf.text.Image;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfWriter;
import java.awt.Toolkit;
import java.io.File;
import java.io.FileOutputStream;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.Date;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.Toolkit;


/**
 *
 * @author Shadow Walker
 */
public class GenerateSalarySlip extends javax.swing.JInternalFrame {
    
    
Connection conn=null;
ResultSet rs=null;
PreparedStatement pst=null;

    /**
     * Creates new form GenerateSalarySlip
     */
    public GenerateSalarySlip() {
        
        initComponents();
        
        conn=DatabaseConnection.connect();  
        Toolkit toolkit = getToolkit();
        Dimension size = toolkit.getScreenSize();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jButton4 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        nic1 = new javax.swing.JTextField();
        des = new javax.swing.JComboBox<>();
        bs = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        lb4 = new javax.swing.JTextField();
        bonusamount = new javax.swing.JTextField();
        med = new javax.swing.JTextField();
        pf = new javax.swing.JTextField();
        pt = new javax.swing.JTextField();
        etf = new javax.swing.JTextField();
        te = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        ns = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        salid = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        search_id = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        month = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        td = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        empid = new javax.swing.JTextField();
        fn = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        mn = new javax.swing.JTextField();
        ln = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jt = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jst = new javax.swing.JComboBox<>();

        setMaximumSize(new java.awt.Dimension(796, 700));
        setMinimumSize(new java.awt.Dimension(796, 700));
        setPreferredSize(new java.awt.Dimension(796, 700));

        jPanel2.setBackground(new java.awt.Color(64, 108, 179));
        jPanel2.setMaximumSize(new java.awt.Dimension(796, 700));
        jPanel2.setMinimumSize(new java.awt.Dimension(796, 700));
        jPanel2.setPreferredSize(new java.awt.Dimension(796, 700));
        jPanel2.setLayout(null);

        jButton4.setBackground(new java.awt.Color(68, 108, 179));
        jButton4.setFont(new java.awt.Font("Corbel", 0, 15)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/generate salary slip.png"))); // NOI18N
        jButton4.setText("Generate Salary Slip");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton4);
        jButton4.setBounds(330, 620, 190, 40);

        jLabel5.setFont(new java.awt.Font("Corbel", 0, 15)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Middle Name :");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(30, 230, 130, 19);

        jLabel16.setFont(new java.awt.Font("Corbel", 0, 15)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Basic Salary :");
        jPanel2.add(jLabel16);
        jLabel16.setBounds(410, 180, 120, 19);

        nic1.setFont(new java.awt.Font("Corbel", 0, 14)); // NOI18N
        jPanel2.add(nic1);
        nic1.setBounds(170, 330, 170, 30);

        des.setFont(new java.awt.Font("Corbel", 0, 14)); // NOI18N
        des.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Designation", "Page Manager", "Designer", "Administrator" }));
        des.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                desActionPerformed(evt);
            }
        });
        jPanel2.add(des);
        des.setBounds(170, 380, 170, 30);

        bs.setFont(new java.awt.Font("Corbel", 0, 14)); // NOI18N
        jPanel2.add(bs);
        bs.setBounds(603, 178, 160, 30);

        jLabel10.setFont(new java.awt.Font("Corbel", 0, 15)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Total Leopard Bees Salary :");
        jPanel2.add(jLabel10);
        jLabel10.setBounds(410, 240, 180, 19);

        jLabel11.setFont(new java.awt.Font("Corbel", 0, 15)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Medical Allowance :");
        jPanel2.add(jLabel11);
        jLabel11.setBounds(410, 340, 150, 19);

        jLabel24.setFont(new java.awt.Font("Corbel", 0, 15)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("Provident Fund :");
        jPanel2.add(jLabel24);
        jLabel24.setBounds(410, 390, 112, 19);

        jLabel26.setFont(new java.awt.Font("Corbel", 0, 15)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setText("Professional Tax :");
        jPanel2.add(jLabel26);
        jLabel26.setBounds(410, 440, 112, 19);

        jLabel17.setFont(new java.awt.Font("Corbel", 0, 15)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("ETF :");
        jPanel2.add(jLabel17);
        jLabel17.setBounds(410, 480, 31, 19);

        jLabel18.setFont(new java.awt.Font("Corbel", 0, 15)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Total Earnings :");
        jPanel2.add(jLabel18);
        jLabel18.setBounds(410, 530, 100, 19);

        jButton5.setBackground(new java.awt.Color(68, 108, 179));
        jButton5.setFont(new java.awt.Font("Corbel", 0, 15)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Delete_40px.png"))); // NOI18N
        jButton5.setText("Clear");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton5);
        jButton5.setBounds(570, 620, 109, 40);

        jLabel13.setFont(new java.awt.Font("Corbel", 0, 15)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Bonus Amount :");
        jPanel2.add(jLabel13);
        jLabel13.setBounds(410, 290, 120, 19);
        jPanel2.add(lb4);
        lb4.setBounds(600, 230, 160, 30);

        bonusamount.setFont(new java.awt.Font("Corbel", 0, 14)); // NOI18N
        bonusamount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bonusamountActionPerformed(evt);
            }
        });
        jPanel2.add(bonusamount);
        bonusamount.setBounds(600, 280, 160, 28);

        med.setFont(new java.awt.Font("Corbel", 0, 14)); // NOI18N
        med.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                medActionPerformed(evt);
            }
        });
        jPanel2.add(med);
        med.setBounds(600, 330, 160, 28);
        jPanel2.add(pf);
        pf.setBounds(600, 380, 160, 33);
        jPanel2.add(pt);
        pt.setBounds(600, 430, 160, 30);
        jPanel2.add(etf);
        etf.setBounds(600, 480, 160, 28);

        te.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                teActionPerformed(evt);
            }
        });
        jPanel2.add(te);
        te.setBounds(600, 530, 160, 30);

        jLabel20.setFont(new java.awt.Font("Corbel", 0, 18)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Money Bag_30px.png"))); // NOI18N
        jLabel20.setText("Net Salary :");
        jPanel2.add(jLabel20);
        jLabel20.setBounds(30, 630, 122, 30);
        jPanel2.add(ns);
        ns.setBounds(170, 620, 134, 40);

        jLabel4.setFont(new java.awt.Font("Corbel", 0, 15)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Salary ID :");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(410, 130, 61, 19);
        jPanel2.add(salid);
        salid.setBounds(603, 129, 160, 31);

        jPanel1.setBackground(new java.awt.Color(68, 108, 179));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jButton3.setBackground(new java.awt.Color(68, 108, 179));
        jButton3.setFont(new java.awt.Font("Corbel", 0, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Search_35px.png"))); // NOI18N
        jButton3.setText("Search");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        search_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                search_idActionPerformed(evt);
            }
        });
        search_id.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                search_idKeyReleased(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Corbel", 0, 15)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Search Employee :");

        jButton1.setBackground(new java.awt.Color(68, 108, 179));
        jButton1.setFont(new java.awt.Font("Corbel", 0, 15)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/View_25px.png"))); // NOI18N
        jButton1.setText("Show Salary Details");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        month.setFont(new java.awt.Font("Corbel", 0, 14)); // NOI18N
        month.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Month", "January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(search_id, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(month, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(search_id, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(month, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel2.add(jPanel1);
        jPanel1.setBounds(20, 40, 760, 70);

        jLabel8.setFont(new java.awt.Font("Corbel", 0, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Page_25px.png"))); // NOI18N
        jLabel8.setText("Salary Slip");
        jPanel2.add(jLabel8);
        jLabel8.setBounds(330, 0, 140, 50);

        jPanel3.setBackground(new java.awt.Color(68, 108, 179));
        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        td.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tdActionPerformed(evt);
            }
        });

        jLabel19.setFont(new java.awt.Font("Corbel", 0, 15)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Total Deductions : ");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
                .addComponent(td, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(445, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(td, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19))
                .addContainerGap())
        );

        jPanel2.add(jPanel3);
        jPanel3.setBounds(370, 120, 410, 490);

        jPanel4.setBackground(new java.awt.Color(68, 108, 179));
        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel4.setLayout(null);

        empid.setFont(new java.awt.Font("Corbel", 0, 14)); // NOI18N
        jPanel4.add(empid);
        empid.setBounds(150, 10, 170, 30);

        fn.setFont(new java.awt.Font("Corbel", 0, 14)); // NOI18N
        jPanel4.add(fn);
        fn.setBounds(150, 60, 170, 30);

        jLabel2.setFont(new java.awt.Font("Corbel", 0, 15)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("First Name :");
        jPanel4.add(jLabel2);
        jLabel2.setBounds(10, 70, 140, 19);

        mn.setFont(new java.awt.Font("Corbel", 0, 14)); // NOI18N
        jPanel4.add(mn);
        mn.setBounds(150, 110, 170, 30);

        ln.setFont(new java.awt.Font("Corbel", 0, 14)); // NOI18N
        jPanel4.add(ln);
        ln.setBounds(150, 160, 170, 30);

        jLabel6.setFont(new java.awt.Font("Corbel", 0, 15)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Last Name :");
        jPanel4.add(jLabel6);
        jLabel6.setBounds(10, 160, 130, 19);

        jLabel21.setFont(new java.awt.Font("Corbel", 0, 15)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("Employee ID :");
        jPanel4.add(jLabel21);
        jLabel21.setBounds(10, 20, 140, 19);

        jLabel7.setFont(new java.awt.Font("Corbel", 0, 15)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("NIC :");
        jPanel4.add(jLabel7);
        jLabel7.setBounds(10, 220, 140, 19);

        jLabel14.setFont(new java.awt.Font("Corbel", 0, 15)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Designation :");
        jPanel4.add(jLabel14);
        jLabel14.setBounds(10, 270, 120, 19);

        jt.setFont(new java.awt.Font("Corbel", 0, 14)); // NOI18N
        jPanel4.add(jt);
        jt.setBounds(150, 310, 170, 30);

        jLabel15.setFont(new java.awt.Font("Corbel", 0, 15)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Job Titile :");
        jPanel4.add(jLabel15);
        jLabel15.setBounds(10, 320, 120, 19);

        jLabel1.setFont(new java.awt.Font("Corbel", 0, 15)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Job Status :");
        jPanel4.add(jLabel1);
        jLabel1.setBounds(10, 370, 71, 19);

        jst.setFont(new java.awt.Font("Corbel", 0, 14)); // NOI18N
        jst.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Job Status", "Full Time", "Part Time" }));
        jPanel4.add(jst);
        jst.setBounds(150, 360, 170, 30);

        jPanel2.add(jPanel4);
        jPanel4.setBounds(20, 120, 340, 490);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        
            String fnn = fn.getText();
            String mnn = mn.getText();
            String lnn = ln.getText();
            String value1 = search_id.getText();
            String value2 = des.getSelectedItem().toString();
            String nic =nic1.getText();
            String jobtitle =jt.getText();
            String jobstatus =jst.getSelectedItem().toString();
            
            String salary1= bs.getText();
            String salid1=salid.getText();
            String totalleopard=lb4.getText();
            String bonus=bonusamount.getText();
            String medical=med.getText();
            String epf=pf.getText();
            String tax=pt.getText();
            String tote=te.getText();
            String totd=td.getText();
            String net=ns.getText();
            
            
            String month2 = month.getSelectedItem().toString();
                                                      
            
            JFileChooser dialog = new JFileChooser();
            dialog.setSelectedFile(new File(fnn +" "+lnn+ " Salary Slip"+".pdf"));
            int dialogResult = dialog.showSaveDialog(null);
            if (dialogResult==JFileChooser.APPROVE_OPTION){
            String filePath = dialog.getSelectedFile().getPath();
           
        try {
            // TODO add your handling code here:        
           
           Document Document1 = new Document();
           PdfWriter myWriter = PdfWriter.getInstance(Document1, new FileOutputStream(filePath));
           Document1.open();
           
           Image img = Image.getInstance("C:\\Users\\MAX\\Desktop\\final tacc slip.png");
           img.scaleAbsolute(90f, 45f);
           img.setAbsolutePosition(475f, 750f);
           Document1.add(img);
           
           Document1.add(new Paragraph("TAC Employee Salary Slip",FontFactory.getFont(FontFactory.TIMES_BOLD,20,Font.BOLD )));
           Document1.add((new Paragraph("Month : " + month2,FontFactory.getFont(FontFactory.TIMES_ROMAN,15,Font.BOLD))));
           Document1.add(new Paragraph("-----------------------------------------------------------------------------------------------------"));
           Document1.add(new Paragraph(new Date().toString()));
           
           Document1.add(new Paragraph("-----------------------------------------------------------------------------------------------------"));
          
           Document1.add((new Paragraph("EMPLOYEE DETAILS",FontFactory.getFont(FontFactory.TIMES_ROMAN,15,Font.BOLD))));
           Document1.add((new Paragraph("First Name: " +fnn,FontFactory.getFont(FontFactory.TIMES_ROMAN,11,Font.PLAIN))));
           Document1.add((new Paragraph("Middle Name: "+mnn,FontFactory.getFont(FontFactory.TIMES_ROMAN,11,Font.PLAIN))));
           Document1.add((new Paragraph("Last Name: "+lnn,FontFactory.getFont(FontFactory.TIMES_ROMAN,11,Font.PLAIN))));
           Document1.add((new Paragraph("Salary ID: " +salid1,FontFactory.getFont(FontFactory.TIMES_ROMAN,11,Font.PLAIN))));
           Document1.add((new Paragraph("NIC: "+nic,FontFactory.getFont(FontFactory.TIMES_ROMAN,11,Font.PLAIN))));
           Document1.add((new Paragraph("Designation: "+value2,FontFactory.getFont(FontFactory.TIMES_ROMAN,11,Font.PLAIN))));
           Document1.add((new Paragraph("Job Title: "+jobtitle,FontFactory.getFont(FontFactory.TIMES_ROMAN,11,Font.PLAIN))));
           Document1.add((new Paragraph("Job Status: "+jobstatus,FontFactory.getFont(FontFactory.TIMES_ROMAN,11,Font.PLAIN))));
           
           Document1.add(new Paragraph("-----------------------------------------------------------------------------------------------------"));
           
           Document1.add(new Paragraph("SALARY",FontFactory.getFont(FontFactory.TIMES_ROMAN,15,Font.BOLD)));
           Document1.add(new Paragraph("Basic Salary: Rs "+salary1,FontFactory.getFont(FontFactory.TIMES_ROMAN,11,Font.PLAIN)));
           
           Document1.add(new Paragraph("-----------------------------------------------------------------------------------------------------"));
           
           Document1.add(new Paragraph("EARNINGS",FontFactory.getFont(FontFactory.TIMES_ROMAN,15,Font.BOLD)));
           Document1.add((new Paragraph("Total Leopard Bees Salary : Rs "+totalleopard,FontFactory.getFont(FontFactory.TIMES_ROMAN,11,Font.PLAIN))));
           Document1.add((new Paragraph("Bonus: Rs "+bonus,FontFactory.getFont(FontFactory.TIMES_ROMAN,11,Font.PLAIN))));
           Document1.add((new Paragraph("Medical Allowance : Rs "+medical,FontFactory.getFont(FontFactory.TIMES_ROMAN,11,Font.PLAIN))));
           
           
           Document1.add(new Paragraph("-----------------------------------------------------------------------------------------------------"));
          
           Document1.add(new Paragraph("DEDUCTIONS",FontFactory.getFont(FontFactory.TIMES_ROMAN,15,Font.BOLD)));
           Document1.add((new Paragraph("Profident Fund : Rs "+epf,FontFactory.getFont(FontFactory.TIMES_ROMAN,11,Font.PLAIN))));
           Document1.add((new Paragraph("Professional TAX: Rs "+tax,FontFactory.getFont(FontFactory.TIMES_ROMAN,11,Font.PLAIN))));
                      
           Document1.add(new Paragraph("-----------------------------------------------------------------------------------------------------"));
           
           Document1.add(new Paragraph("TOTAL EARNINGS",FontFactory.getFont(FontFactory.TIMES_ROMAN,15,Font.BOLD)));
           Document1.add((new Paragraph("Total Earnings: Rs "+tote,FontFactory.getFont(FontFactory.TIMES_ROMAN,11,Font.PLAIN))));
          
           Document1.add(new Paragraph("-----------------------------------------------------------------------------------------------------"));
           
           Document1.add(new Paragraph("TOTAL DEDUCTIONS",FontFactory.getFont(FontFactory.TIMES_ROMAN,15,Font.BOLD)));
           Document1.add((new Paragraph("Total Deductions: Rs "+totd,FontFactory.getFont(FontFactory.TIMES_ROMAN,11,Font.PLAIN))));
           
           Document1.add(new Paragraph("-----------------------------------------------------------------------------------------------------"));
           
           Document1.add(new Paragraph("TOTAL PAYMENT",FontFactory.getFont(FontFactory.TIMES_ROMAN,15,Font.BOLD)));
           Document1.add((new Paragraph("Net Salary Payment: Rs "+net,FontFactory.getFont(FontFactory.TIMES_ROMAN,11,Font.PLAIN)))); 
          
           Document1.add(new Paragraph("-----------------------------------------------------------------------------------------------------"));
           
           
           Document1.newPage();
           Document1.close();  
           JOptionPane.showMessageDialog(null,"Employee Salary Slip is generated successfully");
           
     }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
         
         
     }
     finally {
            
            try{
               rs.close();
               pst.close();
                
            }
            catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
         
            }
     }
   }

      

    }//GEN-LAST:event_jButton4ActionPerformed

    private void search_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_search_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_search_idActionPerformed

    private void search_idKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_search_idKeyReleased
        // TODO add your handling code here:

    }//GEN-LAST:event_search_idKeyReleased

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
     
         try{
        
            String query4="select * from emp where empid=?";
            
            pst =conn.prepareStatement(query4);
            pst.setString(1,search_id.getText());
            rs=pst.executeQuery();
            
            while(rs.next()){
            
            

            
            String add1=rs.getString("empid");
            empid.setText(add1);
            
            String add2=rs.getString("firstname");
            fn.setText(add2);
            
            String add3=rs.getString("middlename");
            mn.setText(add3);
        
            String add4=rs.getString("lastname");
            ln.setText(add4);
            
            String add16=rs.getString("nic");
            nic1.setText(add16);
                               
            String add12=rs.getString("designation");
            des.setSelectedItem(add12);
            
            String add13=rs.getString("jobtitle");
            jt.setText(add13);
            
            String add14=rs.getString("jobstatus");
            jst.setSelectedItem(add14);
            
            String add15=rs.getString("basicSalary");
            bs.setText(add15);
            
            
            
            }
       }
        
        catch(Exception e )
        {
            System.out.println(e);
        }


    
    }//GEN-LAST:event_jButton3ActionPerformed

    private void desActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_desActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_desActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        
        
       search_id.setText("");
        empid.setText("");
        fn.setText("");
        mn.setText("");
        ln.setText("");          
        nic1.setText("");        
        des.setSelectedIndex(0);
        jt.setText("");
        bs.setText("");       
        ln.setText("");
        salid.setText("");
        lb4.setText("");
       jst.setSelectedIndex(0);
        bonusamount.setText("");
        med.setText("");
        pf.setText("");
        pt.setText("");
       te.setText("");
        td.setText("");
      month.setSelectedIndex(0);
      ns.setText("");
      etf.setText("");
    }//GEN-LAST:event_jButton5ActionPerformed

    private void bonusamountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bonusamountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bonusamountActionPerformed

    private void medActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_medActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_medActionPerformed

    private void teActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_teActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_teActionPerformed

    private void tdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tdActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
         try{
        
               
            String employeeid1 = search_id.getText(); 
            String month1 = month.getSelectedItem().toString();
            String query4="select * from salary where employeeid='"+employeeid1+"' AND month='"+month1+"' ";
            
            pst =conn.prepareStatement(query4);
            //pst.setString(1,search_id.getText());
            rs=pst.executeQuery();
            
            while(rs.next()){
                       
            String add7=rs.getString("salaryID");
            salid.setText(add7);    
                
            String add8=rs.getString("leopardTotalSal");
            lb4.setText(add8);
            
            String add9=rs.getString("bonus");
            bonusamount.setText(add9);
            
            String add10=rs.getString("medical");
            med.setText(add10);
            
            String add11=rs.getString("providentFund");
            pf.setText(add11);
            
            String add12=rs.getString("etf");
            etf.setText(add12);
            
            String add13=rs.getString("tax");
            pt.setText(add13);
            
            String add14=rs.getString("totalEarnings");
            te.setText(add14);
            
            String add15=rs.getString("totalDeductions");
            td.setText(add15);
            
            String add16=rs.getString("netSalary");
            ns.setText(add16);
          
            }
        }
            catch(Exception e)
                    {
                    JOptionPane.showMessageDialog(null,"Please select the correct Employee ID and the Month  !");
                    }
        
        
        
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField bonusamount;
    private javax.swing.JTextField bs;
    private javax.swing.JComboBox<String> des;
    private javax.swing.JTextField empid;
    private javax.swing.JTextField etf;
    private javax.swing.JTextField fn;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JComboBox<String> jst;
    private javax.swing.JTextField jt;
    private javax.swing.JTextField lb4;
    private javax.swing.JTextField ln;
    private javax.swing.JTextField med;
    private javax.swing.JTextField mn;
    private javax.swing.JComboBox<String> month;
    private javax.swing.JTextField nic1;
    private javax.swing.JTextField ns;
    private javax.swing.JTextField pf;
    private javax.swing.JTextField pt;
    private javax.swing.JTextField salid;
    private javax.swing.JTextField search_id;
    private javax.swing.JTextField td;
    private javax.swing.JTextField te;
    // End of variables declaration//GEN-END:variables
}
