/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

import ConnectDatabase.DatabaseConnection;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.mail.internet.AddressException;
import javax.mail.internet.InternetAddress;
import javax.swing.JOptionPane;

/**
 *
 * @author Manula Ranzika
 */
public class Interviewee extends javax.swing.JInternalFrame {
    Connection con=null;
    PreparedStatement pst=null;
    ResultSet rs= null;
    
    
    /**    Connection con=null;
    PreparedStatement pst=null;
    ResultSet rs= null;
     * Creates new form Interviewee
     */
    public Interviewee() {
        initComponents();
        con=DatabaseConnection.connect();
    }
    
  //  public static name=namebox.getText();
    
    //email validation method
public static boolean isValidEmailAddress(String email) {
   boolean result = true;
   try {
      InternetAddress emailAddr = new InternetAddress(email);
      emailAddr.validate();
   } catch (AddressException ex) {
      result = false;
   }
   return result;
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Gender = new javax.swing.ButtonGroup();
        jLabel6 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        namebox = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        nicbox = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        emailbox = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        positionbox = new javax.swing.JComboBox();
        genderbox = new javax.swing.JComboBox();
        jButton2 = new javax.swing.JButton();

        setBorder(null);
        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(800, 650));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/intern-2.jpg"))); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 290, 630));

        jPanel1.setBackground(new java.awt.Color(68, 108, 179));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 210, 284, 10));

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Full Name");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 100, -1, -1));

        namebox.setBackground(new java.awt.Color(68, 108, 179));
        namebox.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        namebox.setBorder(null);
        namebox.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                nameboxKeyTyped(evt);
            }
        });
        jPanel1.add(namebox, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 120, 280, -1));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 150, 284, 10));

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Gender");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 160, -1, -1));

        nicbox.setBackground(new java.awt.Color(68, 108, 179));
        nicbox.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        nicbox.setBorder(null);
        nicbox.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                nicboxKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                nicboxKeyTyped(evt);
            }
        });
        jPanel1.add(nicbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 240, 280, -1));

        jButton1.setBackground(new java.awt.Color(68, 108, 179));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Resume_25px.png"))); // NOI18N
        jButton1.setText("Take Interview");
        jButton1.setBorder(null);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 420, 290, 50));

        emailbox.setBackground(new java.awt.Color(68, 108, 179));
        emailbox.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        emailbox.setBorder(null);
        emailbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailboxActionPerformed(evt);
            }
        });
        emailbox.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                emailboxKeyTyped(evt);
            }
        });
        jPanel1.add(emailbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 300, 280, -1));
        jPanel1.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 390, 284, 10));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 270, 284, 10));

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("E-mail");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 280, -1, -1));

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Applying Position");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 340, -1, -1));
        jPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 330, 284, 10));

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("NIC Number");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 220, -1, -1));

        jLabel7.setFont(new java.awt.Font("Corbel", 0, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Interviewee Registration");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 50, -1, -1));

        positionbox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select Position", "Designer", "Page Manager" }));
        jPanel1.add(positionbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 360, 280, -1));

        genderbox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select Gender", "Male", "Female" }));
        jPanel1.add(genderbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 180, 280, -1));

        jButton2.setText("Demo");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 570, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 0, 520, 630));

        setBounds(0, 0, 800, 650);
    }// </editor-fold>//GEN-END:initComponents

    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
           // TODO add your handling code here:
        String name=namebox.getText();
        String gender = genderbox.getSelectedItem().toString();
        String nic = nicbox.getText();
        String mail = emailbox.getText();
        String position = positionbox.getSelectedItem().toString();
        
        Interviewitem i1=new Interviewitem(name);
        
        
        System.out.println(name);
        System.out.println(gender);
        System.out.println(nic);
        System.out.println(mail);
        System.out.println(position);
        
        try{
                if(!"".equals(name) && !"Select Gender".equals(gender) && !"".equals(nic) && !"".equals(mail) && !"Select Position".equals(position)){
                   
                    
                   // String pattern = "^[A-Z0-9._]+@[A-Z0-9.]+\\.[A-Z]+";
                    
                    
                   if(isValidEmailAddress(mail)){ 
                       
                     if(nic.length()==10 && (nic.charAt(9)=='V' ||nic.charAt(9)=='v')){  
                        String q="INSERT INTO interviewee(name,gender,nic,email,position) VALUES ('"+name+"','"+gender+"','"+nic+"','"+mail+"','"+position+"')";                       
                        pst = con.prepareStatement(q);
                        pst.execute();
                    
               //  JOptionPane.showMessageDialog(this, "Item Updated!", "Confirmation", JOptionPane.INFORMATION_MESSAGE);  
                        this.setVisible(false);
                        Interviewitem i2 = new Interviewitem();

                        getParent().add(i2);
                        i2.setVisible(true);
                 
                     
                }
                     else{
                         JOptionPane.showMessageDialog(this, "Invalid NIC format", "ERROR", JOptionPane.ERROR_MESSAGE);
                     
                         }
                            }
                            else{


                                JOptionPane.showMessageDialog(this, "Invalid email format", "ERROR", JOptionPane.ERROR_MESSAGE);

                            }    
                }
                
                else{
                JOptionPane.showMessageDialog(this, "All fields are mandetory!", "ERROR", JOptionPane.ERROR_MESSAGE);
                }
                }
                catch(Exception e){System.out.println(e);}
        
        
        
        
       // d2.setVisible(true);
        
        //try 2
       // JInternalFrame newFrame = JInternalFrame();
        //d2.setBounds(10, 10, 100, 100);
        //d2.setVisible(true);
//        getParent().add(i2);
//        i2.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void emailboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailboxActionPerformed

    private void nameboxKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nameboxKeyTyped
        // TODO add your handling code here:
        
       char enter = evt.getKeyChar();
        if((Character.isDigit(enter))){
            
            evt.consume();
        
        }
      
    }//GEN-LAST:event_nameboxKeyTyped

    private void nicboxKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nicboxKeyPressed
        // TODO add your handling code here:

        
        
    
    }//GEN-LAST:event_nicboxKeyPressed

    private void emailboxKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_emailboxKeyTyped
        // TODO add your handling code here:
        

    
    }//GEN-LAST:event_emailboxKeyTyped

    private void nicboxKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nicboxKeyTyped

    
    }//GEN-LAST:event_nicboxKeyTyped

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
                        this.setVisible(false);
                        Interviewitem i2 = new Interviewitem();

                        getParent().add(i2);
                        i2.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup Gender;
    private javax.swing.JTextField emailbox;
    private javax.swing.JComboBox genderbox;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JTextField namebox;
    private javax.swing.JTextField nicbox;
    private javax.swing.JComboBox positionbox;
    // End of variables declaration//GEN-END:variables
}
