/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

import ConnectDatabase.DatabaseConnection;
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author Manula Ranzika
 */
public class NewbeeAdmin extends javax.swing.JInternalFrame {

    Connection con = null;
    PreparedStatement pst = null;
    ResultSet rs = null;

    /**
     * Creates new form NewbeeAdmin
     */
    public NewbeeAdmin() {
        initComponents();
        con = DatabaseConnection.connect();

        tableLoad L1 = new tableLoad();
        L1.tableload_designer();

        tableLoad L2 = new tableLoad();
        L2.tableload_int();
    }

    public class tableLoad {

        public void tableload_designer() {
            try {
                String sql = "SELECT taskID,task,type FROM newbee";

                pst = con.prepareStatement(sql);
                rs = pst.executeQuery();

                jTable3.setModel(DbUtils.resultSetToTableModel(rs));
            } catch (Exception e) {
            }

        }

        public void tableload_int() {
            try {
                String sql = "SELECT name,nic,position,status FROM interviewee";

                pst = con.prepareStatement(sql);
                rs = pst.executeQuery();

                jTable1.setModel(DbUtils.resultSetToTableModel(rs));
            } catch (Exception e) {
            }

        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        IDlabel = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        taskBox = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        typeBox = new javax.swing.JComboBox();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        intnic = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        intname = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton6 = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(800, 650));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Question ID");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 80, -1, -1));

        IDlabel.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(IDlabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(104, 80, -1, -1));

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Task");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 153, -1, -1));

        taskBox.setColumns(20);
        taskBox.setRows(5);
        jScrollPane2.setViewportView(taskBox);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(104, 153, 252, 189));

        jButton1.setBackground(new java.awt.Color(68, 108, 179));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Add");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(464, 319, -1, -1));

        jButton2.setBackground(new java.awt.Color(68, 108, 179));
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Update");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(541, 319, -1, -1));

        jButton3.setBackground(new java.awt.Color(68, 108, 179));
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Delete");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(626, 319, -1, -1));

        jButton4.setBackground(new java.awt.Color(68, 108, 179));
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("Clear");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(374, 319, -1, -1));

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("For");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 115, -1, -1));

        typeBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select designation type", "Designers", "Page Managers" }));
        typeBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                typeBoxActionPerformed(evt);
            }
        });
        getContentPane().add(typeBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(104, 112, 252, -1));

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable3MouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(jTable3);

        getContentPane().add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(374, 112, 323, 189));

        jCheckBox1.setBackground(new java.awt.Color(68, 108, 179));
        jCheckBox1.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBox1.setText("Show Designer Tasks");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jCheckBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 71, -1, -1));

        jCheckBox2.setBackground(new java.awt.Color(68, 108, 179));
        jCheckBox2.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBox2.setText("Show Page Manager Tasks");
        jCheckBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox2ActionPerformed(evt);
            }
        });
        getContentPane().add(jCheckBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(374, 71, -1, -1));

        jPanel3.setBackground(new java.awt.Color(68, 108, 179));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Promote Interviewee to intern", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Corbel", 0, 15), new java.awt.Color(0, 255, 255))); // NOI18N
        jPanel3.setForeground(new java.awt.Color(0, 204, 204));

        jLabel2.setFont(new java.awt.Font("Corbel", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Interviewee NIC");

        jLabel5.setFont(new java.awt.Font("Corbel", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Interviewee Name");

        intname.setFont(new java.awt.Font("Corbel", 0, 14)); // NOI18N
        intname.setForeground(new java.awt.Color(255, 255, 255));

        jButton5.setText("Promote");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel5))
                .addGap(21, 21, 21)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(intname)
                    .addComponent(intnic)
                    .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, 234, Short.MAX_VALUE))
                .addGap(83, 83, 83))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(intnic, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(intname))
                .addGap(37, 37, 37)
                .addComponent(jButton5)
                .addContainerGap(51, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 370, 450, 230));

        jPanel1.setBackground(new java.awt.Color(68, 108, 179));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(68, 108, 179));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Add tasks for Newbees", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 15), new java.awt.Color(0, 255, 255))); // NOI18N
        jPanel2.setForeground(new java.awt.Color(0, 204, 204));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 748, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 292, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 760, 320));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 380, 300, 150));

        jButton6.setText("Interviewee Report");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 540, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 800, 620));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:UPDATE

        int x = JOptionPane.showConfirmDialog(null, "Do you want to update Newbee Item?");
        if (x == 0) {
            String type = typeBox.getSelectedItem().toString();
            String id = IDlabel.getText();
            String task = taskBox.getText();

            String sql = "UPDATE newbee SET task='" + task + "',type='" + type + "' where taskID='" + id + "'";

            if ("".equals(task) || "Select designation type".equals(type)) {

                JOptionPane.showMessageDialog(this, "Please Enter task and select the designation", "ERROR", JOptionPane.ERROR_MESSAGE);

            } else {

                try {
                    pst = con.prepareStatement(sql);
                    pst.execute();

                    tableLoad L1 = new tableLoad();
                    L1.tableload_designer();
                    JOptionPane.showMessageDialog(this, "Item Updated!", "Confirmation", JOptionPane.INFORMATION_MESSAGE);

                } catch (SQLException | HeadlessException e) {
                }
            }
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

//INSERT        // TODO add your handling code here:
        String type = typeBox.getSelectedItem().toString();
        String task = taskBox.getText();
        if ("".equals(task) || "Select designation type".equals(type)) {

            JOptionPane.showMessageDialog(this, "Please Enter task and select the designation", "ERROR", JOptionPane.ERROR_MESSAGE);

        } else {
            try {

                String q = "INSERT INTO newbee(type,task) VALUES('" + type + "','" + task + "')";
                pst = con.prepareStatement(q);
                pst.execute();
                tableLoad L1 = new tableLoad();
                L1.tableload_designer();

            } catch (Exception e) {
                System.out.println(e);
            }

        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void typeBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_typeBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_typeBoxActionPerformed

    private void jTable3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable3MouseClicked
        // TODO add your handling code here:

        int row = jTable3.getSelectedRow();
        String type = jTable3.getValueAt(row, 2).toString();

        String id = jTable3.getValueAt(row, 0).toString();
        //    String type=jTable1.getValueAt(row, 3).toString();
        String task = jTable3.getValueAt(row, 1).toString();

        IDlabel.setText(id);
        taskBox.setText(task);
        typeBox.setSelectedItem(type);

    }//GEN-LAST:event_jTable3MouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        //DELETE

        int x = JOptionPane.showConfirmDialog(null, "Do you want to newbee item?");

        if (x == 0) {
            String id = IDlabel.getText();

            String sql = "DELETE FROM newbee WHERE taskID='" + id + "'";

            try {
                pst = con.prepareStatement(sql);
                pst.execute();

                //     tableLoadB L1=new tableLoadB();
                tableLoad L1 = new tableLoad();
                L1.tableload_designer();
                JOptionPane.showMessageDialog(this, "Item Deleted!", "Confirmation", JOptionPane.INFORMATION_MESSAGE);

            } catch (SQLException | HeadlessException e) {
            }

        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        // ONLY DESIGNERS

        if (jCheckBox2.isSelected() == false) {

            String sql = "SELECT * from newbee WHERE type = 'Designers'";
            try {

                pst = con.prepareStatement(sql);
                rs = pst.executeQuery(); //rs is result set
                jTable3.setModel(DbUtils.resultSetToTableModel(rs));
            } catch (Exception e) {
            }

    }//GEN-LAST:event_jCheckBox1ActionPerformed
        else {
            String sql = "SELECT * from newbee";
            try {

                pst = con.prepareStatement(sql);
                rs = pst.executeQuery(); //rs is result set
                jTable3.setModel(DbUtils.resultSetToTableModel(rs));

            } catch (Exception e) {
            }

        }
    }

    private void jCheckBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox2ActionPerformed
        // only pManagers visible
        if (jCheckBox1.isSelected() == false) {
            String sql = "SELECT * from newbee WHERE type = 'Page Managers'";
            try {

                pst = con.prepareStatement(sql);
                rs = pst.executeQuery(); //rs is result set
                jTable3.setModel(DbUtils.resultSetToTableModel(rs));

    }//GEN-LAST:event_jCheckBox2ActionPerformed
/*
    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked

        // TODO add your handling code here:
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed
*/ 
catch (Exception e) {
            }
        } else {
            String sql = "SELECT * from newbee";
            try {

                pst = con.prepareStatement(sql);
                rs = pst.executeQuery(); //rs is result set
                jTable3.setModel(DbUtils.resultSetToTableModel(rs));

            } catch (Exception e) {
            }

        }

    }

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        //CLEAR BUTTON

        IDlabel.setText("");
        taskBox.setText("");
        typeBox.setSelectedItem("Select designation type");
        // typeBox.setSelectedItem("");
    }

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:

        String internic = intnic.getText();

        String sql = "SELECT name FROM interviewee WHERE nic='" + internic + "'";

        try {
            pst = con.prepareStatement(sql);
            rs = pst.executeQuery(sql);
            //  jTable1.setModel(DbUtils.resultSetToTableModel(rs));
            //     
            //   String sql2 = "SELECT firstname from emp WHERE empid='"+emp+"'";

            while (rs.next()) {
                // int usercol =  rs.findColumn("password");

                //  get Designation
                String intername = rs.getString("name");
                System.out.println(intername);

                intname.setText(intername);

                String sql2 = "UPDATE interviewee SET status='intern' where nic='" + internic + "'";
                pst = con.prepareStatement(sql2);
                pst.execute(sql2);
                JOptionPane.showMessageDialog(this, "interviewee made intern!!", "Confirmation", JOptionPane.INFORMATION_MESSAGE);
                
                tableLoad L2 = new tableLoad();
                L2.tableload_int();
            
            }
            
        } catch (Exception e) {
        }

    }

                               

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {                                     

        // set NIC to promote
        
        int row = jTable1.getSelectedRow();
        String nic = jTable1.getValueAt(row,1).toString();
        String name = jTable1.getValueAt(row,0).toString();
        intnic.setText(nic);
        intname.setText(name);
        
    }                                    

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
        
        String report="C:\\Users\\MAX\\Documents\\NetBeansProjects\\TA Consultancies\\src\\Reports\\IntervieweeReport.jrxml";
        try
        {
            JasperReport jr= JasperCompileManager.compileReport(report);
            JasperPrint jp= JasperFillManager.fillReport(jr,null, con);
            JasperViewer.viewReport(jp,false);

        }
        catch(Exception e)
        {
            System.out.println("Error:"+e);
        }
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel IDlabel;
    private javax.swing.JLabel intname;
    private javax.swing.JTextField intnic;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable3;
    private javax.swing.JTextArea taskBox;
    private javax.swing.JComboBox typeBox;
    // End of variables declaration//GEN-END:variables
}
