/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

import ConnectDatabase.DatabaseConnection;
import com.toedter.calendar.JDateChooser;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Locale;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Shadow Walker
 */
public class UpdateEmployee1 extends javax.swing.JInternalFrame {
    
     Connection con = null;
    PreparedStatement pst =null;
    ResultSet rs= null;

    /**
     * Creates new form UpdateEmployee1
     */
    public UpdateEmployee1() {
        initComponents();
        con = DatabaseConnection.connect();        
        tableLoad();
        
    }
    
    public void tableLoad()
    {
        try
        {
            String sqlquery ="SELECT empid,firstname,middlename,lastname,nic,joineddate,designation,email FROM emp";
            pst =con.prepareStatement(sqlquery);
            rs =pst.executeQuery();
            
            emptable.setModel(DbUtils.resultSetToTableModel(rs));
        }
       
        catch(Exception e)
        {
            System.out.println(e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        emptable = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        gn = new javax.swing.JComboBox<>();
        jLabel19 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jd = new javax.swing.JTextField();
        jst = new javax.swing.JComboBox<>();
        add1x = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        city = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        mn = new javax.swing.JTextField();
        cn = new javax.swing.JTextField();
        em = new javax.swing.JTextField();
        ln = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        fn = new javax.swing.JTextField();
        empid = new javax.swing.JTextField();
        des = new javax.swing.JComboBox<>();
        jt = new javax.swing.JTextField();
        bs = new javax.swing.JTextField();
        add2x = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel22 = new javax.swing.JLabel();
        pwd = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        nic1 = new javax.swing.JTextField();
        dob2 = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        search = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();

        setMaximumSize(new java.awt.Dimension(796, 700));
        setMinimumSize(new java.awt.Dimension(796, 700));
        setPreferredSize(new java.awt.Dimension(796, 700));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Corbel", 0, 15)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Search Employee :");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 120, 40));

        emptable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Employee ID", "First Name", "Middle Name", "Last Name", "NIC", "Joined Date", "Designation", "Email"
            }
        ));
        emptable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                emptableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(emptable);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 730, 60));

        jPanel5.setBackground(new java.awt.Color(64, 108, 179));
        jPanel5.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel5.setForeground(new java.awt.Color(255, 255, 255));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Corbel", 0, 15)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Date Of Birth :");
        jPanel5.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, 130, -1));

        jLabel7.setFont(new java.awt.Font("Corbel", 0, 15)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Gender:");
        jPanel5.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 140, -1));

        gn.setFont(new java.awt.Font("Corbel", 0, 14)); // NOI18N
        gn.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Gender", "Male", "Female" }));
        gn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gnActionPerformed(evt);
            }
        });
        jPanel5.add(gn, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 230, 170, 30));

        jLabel19.setFont(new java.awt.Font("Corbel", 0, 15)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Address line 02 :");
        jPanel5.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 30, 130, -1));

        jLabel9.setFont(new java.awt.Font("Corbel", 0, 15)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Address line 01 :");
        jPanel5.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 350, 130, -1));

        jLabel10.setFont(new java.awt.Font("Corbel", 0, 15)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Contact No : ");
        jPanel5.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 130, 120, -1));

        jLabel1.setFont(new java.awt.Font("Corbel", 0, 15)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Job Status :");
        jPanel5.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 420, -1, -1));

        jLabel16.setFont(new java.awt.Font("Corbel", 0, 15)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Basic Salary :");
        jPanel5.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 340, 120, -1));

        jLabel15.setFont(new java.awt.Font("Corbel", 0, 15)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Job Titile :");
        jPanel5.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 300, 120, -1));

        jLabel14.setFont(new java.awt.Font("Corbel", 0, 15)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Designation :");
        jPanel5.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 250, 120, -1));

        jLabel13.setFont(new java.awt.Font("Corbel", 0, 15)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Joined Date :");
        jPanel5.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 210, 110, -1));

        jLabel11.setFont(new java.awt.Font("Corbel", 0, 15)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Email :");
        jPanel5.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 170, 80, -1));

        jLabel12.setFont(new java.awt.Font("Corbel", 0, 15)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("City :");
        jPanel5.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 90, 80, -1));

        jLabel6.setFont(new java.awt.Font("Corbel", 0, 15)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("NIC :");
        jPanel5.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 140, -1));

        jd.setFont(new java.awt.Font("Corbel", 0, 14)); // NOI18N
        jPanel5.add(jd, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 200, 180, 30));

        jst.setFont(new java.awt.Font("Corbel", 0, 14)); // NOI18N
        jst.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Job Status", "Full Time", "Part Time" }));
        jPanel5.add(jst, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 410, 180, 30));

        add1x.setFont(new java.awt.Font("Corbel", 0, 14)); // NOI18N
        add1x.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add1xActionPerformed(evt);
            }
        });
        jPanel5.add(add1x, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 340, 170, 65));

        jLabel5.setFont(new java.awt.Font("Corbel", 0, 15)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Last Name :");
        jPanel5.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 130, -1));

        city.setFont(new java.awt.Font("Corbel", 0, 14)); // NOI18N
        jPanel5.add(city, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 80, 180, 30));

        jLabel21.setFont(new java.awt.Font("Corbel", 0, 15)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("Employee ID :");
        jPanel5.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 140, -1));

        jLabel2.setFont(new java.awt.Font("Corbel", 0, 15)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("First Name :");
        jPanel5.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 140, -1));

        mn.setFont(new java.awt.Font("Corbel", 0, 14)); // NOI18N
        jPanel5.add(mn, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 100, 170, 30));

        cn.setFont(new java.awt.Font("Corbel", 0, 14)); // NOI18N
        jPanel5.add(cn, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 120, 180, 30));

        em.setFont(new java.awt.Font("Corbel", 0, 14)); // NOI18N
        jPanel5.add(em, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 160, 180, 30));

        ln.setFont(new java.awt.Font("Corbel", 0, 14)); // NOI18N
        jPanel5.add(ln, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 140, 170, 30));

        jLabel4.setFont(new java.awt.Font("Corbel", 0, 15)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Middle Name :");
        jPanel5.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 130, -1));

        fn.setFont(new java.awt.Font("Corbel", 0, 14)); // NOI18N
        jPanel5.add(fn, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 60, 170, 30));

        empid.setFont(new java.awt.Font("Corbel", 0, 14)); // NOI18N
        jPanel5.add(empid, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 20, 170, 30));

        des.setFont(new java.awt.Font("Corbel", 0, 14)); // NOI18N
        des.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Designation", "Page Manager", "Designer", "Administrator" }));
        des.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                desActionPerformed(evt);
            }
        });
        jPanel5.add(des, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 240, 180, 30));

        jt.setFont(new java.awt.Font("Corbel", 0, 14)); // NOI18N
        jPanel5.add(jt, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 290, 180, 30));

        bs.setFont(new java.awt.Font("Corbel", 0, 14)); // NOI18N
        jPanel5.add(bs, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 330, 180, 30));

        add2x.setFont(new java.awt.Font("Corbel", 0, 14)); // NOI18N
        add2x.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add2xActionPerformed(evt);
            }
        });
        jPanel5.add(add2x, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 10, 180, 65));

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel5.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 0, 60, 500));

        jLabel22.setFont(new java.awt.Font("Corbel", 0, 12)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("                    <Employee ID>");
        jPanel5.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 70, 160, 30));

        pwd.setFont(new java.awt.Font("Corbel", 0, 14)); // NOI18N
        jPanel5.add(pwd, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 370, 180, 30));

        jLabel17.setFont(new java.awt.Font("Corbel", 0, 15)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Password :");
        jPanel5.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 380, 90, -1));

        nic1.setFont(new java.awt.Font("Corbel", 0, 14)); // NOI18N
        jPanel5.add(nic1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 180, 170, 30));

        dob2.setFont(new java.awt.Font("Corbel", 0, 14)); // NOI18N
        jPanel5.add(dob2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 280, 170, 30));

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 730, 460));
        getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 640, 710, 0));

        jPanel2.setBackground(new java.awt.Color(64, 108, 179));

        jButton1.setBackground(new java.awt.Color(68, 108, 179));
        jButton1.setFont(new java.awt.Font("Corbel", 0, 15)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Trash_30px.png"))); // NOI18N
        jButton1.setText("Remove Employee");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(68, 108, 179));
        jButton2.setFont(new java.awt.Font("Corbel", 0, 15)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Refresh_30px.png"))); // NOI18N
        jButton2.setText("Update Employee");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(68, 108, 179));
        jButton4.setFont(new java.awt.Font("Corbel", 0, 15)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Delete_40px.png"))); // NOI18N
        jButton4.setText("Clear");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchActionPerformed(evt);
            }
        });
        search.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                searchKeyReleased(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(68, 108, 179));
        jButton3.setFont(new java.awt.Font("Corbel", 0, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Search_35px.png"))); // NOI18N
        jButton3.setText("Search");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(333, 333, 333)
                        .addComponent(jButton1)
                        .addGap(18, 18, 18)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(183, 183, 183)
                        .addComponent(search, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(131, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(144, 144, 144)
                    .addComponent(jButton2)
                    .addContainerGap(521, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(search))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 550, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4))
                .addGap(39, 39, 39))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                    .addContainerGap(601, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(39, 39, 39)))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 840, 690));
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, -10, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
       try{
        
            String query4="select * from emp where empid=?";
            
            pst =con.prepareStatement(query4);
            pst.setString(1,search.getText());
            rs=pst.executeQuery();
            
            while(rs.next()){
            
            

            
            String add1=rs.getString("empid");
            empid.setText(add1);
            
            String add2=rs.getString("firstname");
            fn.setText(add2);
            
            String add3=rs.getString("middlename");
            mn.setText(add3);
        
            String add4=rs.getString("lastname");
            ln.setText(add4);
            
            String add16=rs.getString("nic");
            nic1.setText(add16);
            
            
            String add5=rs.getString("gender");
            gn.setSelectedItem(add5);
            
        
                    
            String add6=rs.getString("password");
            pwd.setText(add6);
            
            String add7=rs.getString("address");
            add1x.setText(add7);
            
            String add17=rs.getString("dob");
            dob2.setText(add17);
            
            String add18=rs.getString("joineddate");
            jd.setText(add18);
            
            String add8=rs.getString("address2");
            add2x.setText(add8);
            
            String add9=rs.getString("city");
            city.setText(add9);
            
            String add10=rs.getString("contact");
            cn.setText("0"+add10);
            
            String add11=rs.getString("email");
            em.setText(add11);
            
            String add12=rs.getString("designation");
            des.setSelectedItem(add12);
            
            String add13=rs.getString("jobtitle");
            jt.setText(add13);
            
            String add14=rs.getString("jobstatus");
            jst.setSelectedItem(add14);
            
            String add15=rs.getString("basicSalary");
            bs.setText(add15);
            
            
            
            }
       }
        
        catch(Exception e )
        {
            System.out.println(e);
        }

    }//GEN-LAST:event_jButton3ActionPerformed

    private void gnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_gnActionPerformed

    private void desActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_desActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_desActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
          
        
        String empid1 = empid.getText();
        String fnx = fn.getText();
        String mnx = mn.getText();
        String lnx1 = ln.getText();
        String pwdx = pwd.getText();
        String nicx = nic1.getText();
        String genderx = gn.getSelectedItem().toString();
        String dobx =dob2.getText();
        String addx = add1x.getText();
        String adddx = add2x.getText();
        String cityx = city.getText();
        String cnx = cn.getText();
        String emx = em.getText();
        String jdx = jd.getText();
        String desx = des.getSelectedItem().toString();
        String jtx = jt.getText();
        String bsx = bs.getText();  
        
        String jstx = jst.getSelectedItem().toString();
        
        Validation val1 =new Validation();
        
 if(gn.getSelectedIndex()==0 || des.getSelectedIndex()==0 || jst.getSelectedIndex()==0)
 {
     JOptionPane.showMessageDialog(null, "Please Select all Options !");
 }
 
 else{
     if(val1.validatemail(emx)){
            if(val1.validatePhone(cnx)){
                 if(nicx.length()==10 && (nicx.charAt(9)=='V' || nicx.charAt(9)=='v')){
                      if(!bsx.isEmpty() && bsx.matches(("((-|\\+)?[0-9]+(\\.[0-9]+)?)+"))){
                          if(!dobx.isEmpty() && !jdx.isEmpty()){
                                int x = JOptionPane.showConfirmDialog(null,"Do you really want to update ?");
        
                                if(x==0)
                                { 
                                    String query2 = " Update emp SET firstname = '"+fnx+"',middlename = '"+mnx+"',lastname = '"+lnx1+"', password = '"+pwdx+"' ,nic='"+nicx+"',gender = '"+genderx+"', dob = '"+dobx+"',address ='"+addx+"',address2 ='"+adddx+"', city ='"+cityx+"',contact ='"+cnx+"',email='"+emx+"',basicSalary='"+bsx+"' ,joineddate='"+jdx+"',designation='"+desx+"',jobtitle='"+jtx+"',jobstatus= '"+jstx+"'  WHERE empid = '"+empid1+"' ";
                                    try {
                                        pst =con.prepareStatement(query2);
                                         pst.execute();

                                         tableLoad();
                                         JOptionPane.showMessageDialog(null, "Employee details updated successfully !");
                                    } 
                                    catch (SQLException e) 
                                    { System.out.println(e);
                                    JOptionPane.showMessageDialog(null, "Employee NIC already entered !");}
                                } else {}
                            }else{JOptionPane.showMessageDialog(null,"Please complete date fields!");}
                        }else {JOptionPane.showMessageDialog(null,"Please enter a valid Basic Salary !");}
                    }else {JOptionPane.showMessageDialog(null,"Please enter a valid NIC !");}
                }else{JOptionPane.showMessageDialog(null,"Please enter a valid Contact Number !");}
            }else{JOptionPane.showMessageDialog(null,"Please enter a valid Email Address !");}
         
         
    }//GEN-LAST:event_jButton2ActionPerformed
    }
    
    private void emptableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_emptableMouseClicked
        // TODO add your handling code here:
        
      int r = emptable.getSelectedRow();
      
      String eid= emptable.getValueAt(r,0).toString();
      
      try
      {
       String query5="select * from emp where empid='"+eid+"'";
            
            pst =con.prepareStatement(query5);
            
            rs=pst.executeQuery();
            
            while(rs.next()){         
                      
            String add1=rs.getString("empid");
            empid.setText(add1);
            
            String add2=rs.getString("firstname");
            fn.setText(add2);
            
            String add3=rs.getString("middlename");
            mn.setText(add3);
        
            String add4=rs.getString("lastname");
            ln.setText(add4);
            
            String add16=rs.getString("nic");
            nic1.setText(add16);
            
            
            String add5=rs.getString("gender");
            gn.setSelectedItem(add5);
                   
                    
            String add6=rs.getString("password");
            pwd.setText(add6);
            
            String add7=rs.getString("address");
            add1x.setText(add7);
            
            String add17=rs.getString("dob");
            dob2.setText(add17);
            
            String add18=rs.getString("joineddate");
            jd.setText(add18);
            
            String add8=rs.getString("address2");
            add2x.setText(add8);
            
            String add9=rs.getString("city");
            city.setText(add9);
            
            String add10=rs.getString("contact");
            cn.setText("0"+add10);
            
            String add11=rs.getString("email");
            em.setText(add11);
            
            String add12=rs.getString("designation");
            des.setSelectedItem(add12);
            
            String add13=rs.getString("jobtitle");
            jt.setText(add13);
            
            String add14=rs.getString("jobstatus");
            jst.setSelectedItem(add14);
            
            String add15=rs.getString("basicSalary");
            bs.setText(add15);
            
            }
      }       
            catch(Exception e)
                    {
                    System.out.println(e);
                    }
    }//GEN-LAST:event_emptableMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        int x = JOptionPane.showConfirmDialog(null,"Do you really want to remove ?");
        
        if(x==0)
                {
                    String ID =empid.getText();
                   try{ 
                       
                  
                    String sql3= " DELETE FROM emp WHERE empid = '"+ID+"'";
                    pst =con.prepareStatement(sql3);
                    pst.execute();
                 JOptionPane.showMessageDialog(null, "Employee removed succesfully !");
                    tableLoad();
                                
                   }
                   catch (Exception e)
                   {
                       System.out.println(e);
                   }
    }//GEN-LAST:event_jButton1ActionPerformed
    }
    private void add1xActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add1xActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_add1xActionPerformed

    private void add2xActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add2xActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_add2xActionPerformed

    private void searchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchKeyReleased
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_searchKeyReleased

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        
        search.setText("");
        empid.setText("");
        fn.setText("");
        mn.setText("");
        ln.setText("");
        jd.setText("");
        
        gn.setSelectedIndex(0);
        nic1.setText("");
        dob2.setText("");
        add1x.setText("");
        add2x.setText("");
        city.setText("");
        cn.setText("");
        em.setText("");
        des.setSelectedIndex(0);
        jt.setText("");
        bs.setText("");
        pwd.setText("");
        ln.setText("");
       jst.setSelectedIndex(0);
        
                    
                     
    }//GEN-LAST:event_jButton4ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField add1x;
    private javax.swing.JTextField add2x;
    private javax.swing.JTextField bs;
    private javax.swing.JTextField city;
    private javax.swing.JTextField cn;
    private javax.swing.JComboBox<String> des;
    private javax.swing.JTextField dob2;
    private javax.swing.JTextField em;
    private javax.swing.JTextField empid;
    private javax.swing.JTable emptable;
    private javax.swing.JTextField fn;
    private javax.swing.JComboBox<String> gn;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField jd;
    private javax.swing.JComboBox<String> jst;
    private javax.swing.JTextField jt;
    private javax.swing.JTextField ln;
    private javax.swing.JTextField mn;
    private javax.swing.JTextField nic1;
    private javax.swing.JTextField pwd;
    private javax.swing.JTextField search;
    // End of variables declaration//GEN-END:variables
}
