/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

import ConnectDatabase.DatabaseConnection;
import static com.sun.org.apache.xerces.internal.util.FeatureState.is;
import com.toedter.calendar.JDateChooser;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import net.proteanit.sql.DbUtils;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author shannon
 */
public class viewFeedback extends javax.swing.JInternalFrame {

    Connection con = null; 
    PreparedStatement pst = null;    
    ResultSet rs = null;
    ResultSet rs1 = null;
    /**
     * Creates new form viewFeedback
     */
    public viewFeedback() {
        initComponents();
                
        //Connect to DB
        con = DatabaseConnection.connect();
        
        //load table
        //tableload();
        
    }
    
     public void tableload()
    {
        try{
            String sql = "SELECT fbID,jobID,custID,fbDate,comment,replyDeadline,replyDate FROM feedback";
            pst = con.prepareStatement(sql);
            
            rs = pst.executeQuery();
            
            feedB.setModel(DbUtils.resultSetToTableModel(rs));
            
        } catch(Exception e){
            System.out.println(e); 
        }
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        search1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        feedB = new javax.swing.JTable();
        d2 = new com.toedter.calendar.JDateChooser();
        d1 = new com.toedter.calendar.JDateChooser();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setPreferredSize(new java.awt.Dimension(784, 632));

        jPanel1.setBackground(new java.awt.Color(68, 108, 179));
        jPanel1.setPreferredSize(new java.awt.Dimension(798, 649));

        jLabel1.setBackground(new java.awt.Color(68, 108, 179));
        jLabel1.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("From:");

        jLabel2.setBackground(new java.awt.Color(68, 108, 179));
        jLabel2.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("To:");

        search1.setBackground(new java.awt.Color(68, 108, 179));
        search1.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        search1.setForeground(new java.awt.Color(255, 255, 255));
        search1.setText("Search");
        search1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                search1ActionPerformed(evt);
            }
        });

        feedB.setBackground(new java.awt.Color(68, 108, 179));
        feedB.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        feedB.setForeground(new java.awt.Color(51, 255, 255));
        feedB.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "FeedbackID", "CustomerID", "FeedDate", "Remarks", "ReplyDeadline", "RepliedDate"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        feedB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                feedBMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(feedB);

        d2.setDateFormatString("yyyy-MM-dd");

        d1.setDateFormatString("yyyy-MM-dd");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(139, 139, 139)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(191, 191, 191)
                                .addComponent(search1, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(d1, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(38, 38, 38)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(d2, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 712, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(d2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(d1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(26, 26, 26)
                .addComponent(search1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(66, 66, 66)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(155, 155, 155))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 757, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 585, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void feedBMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_feedBMouseClicked
        // TODO add your handling code here:
        
      /* int rw=feedB.getSelectedRow();
        
        String id=feedB.getValueAt(rw,1).toString(); //this is assigning ID to variable id
        String Fid=feedB.getValueAt(rw,0).toString();
        System.out.println(Fid);
        
        this.setVisible(false); //close current form
	      reply r1=new reply(id,Fid); //passing id
        
	      getParent().add(r1).setVisible(true); //displaying in form2
        */
        String sql1;
        try{
            
            int rw=feedB.getSelectedRow();
        
        String id=feedB.getValueAt(rw,1).toString(); //this is assigning ID to variable id
        String Fid=feedB.getValueAt(rw,0).toString();
        String fee=feedB.getValueAt(rw,4).toString();
        
        sql1= "SELECT reply FROM feedback WHERE fbid="+Fid+ ";";
        PreparedStatement pst4 = con.prepareStatement(sql1);
            ResultSet rs5 = pst4.executeQuery();
       
        
        String rep ="m";
         try{
             rs5.next();
            rep=rs5.getString(1);
         System.out.println(rep);
             if(rep==null)
	  { System.out.println(rep);
	      this.setVisible(false); //close current form
	      reply r1=new reply(id,Fid,fee); //passing id
        
	      getParent().add(r1).setVisible(true); //displaying in form2
	  }   
            else{
            JOptionPane.showMessageDialog(null,"Already replied !");
	  }} 
         catch(Exception ex){
             System.out.println(ex);
         }
         }
        catch(Exception ex){
            System.out.println(ex);
        }
        
    }//GEN-LAST:event_feedBMouseClicked

    private void search1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_search1ActionPerformed
        // TODO add your handling code here:
        
        String da1=((JTextField)d1.getDateEditor().getUiComponent()).getText(); 
        String da2=((JTextField)d2.getDateEditor().getUiComponent()).getText(); 
        if(!da1.isEmpty() && !da2.isEmpty())
        {
            SimpleDateFormat dFormat = new SimpleDateFormat("yyyy-MM-dd");
            String fDate= dFormat.format(d1.getDate());
            String tDate= dFormat.format(d2.getDate());

            jScrollPane1.setVisible(true);
            DefaultTableModel model1 = (DefaultTableModel) feedB.getModel();
            String sql;

            try{
	  sql = "SELECT fbID,custID,jobID,fbDate,comment,replyDeadline,replyDate FROM feedback WHERE (fbDate BETWEEN '" +fDate+ "' AND '" +tDate+ "');";
	  pst = con.prepareStatement(sql);
	  rs = pst.executeQuery();
	  model1.setRowCount(0);      

	  feedB.setModel(DbUtils.resultSetToTableModel(rs));

            } catch(Exception e){
	  System.out.println(e);
            }
        }
        else
        {
            JOptionPane.showMessageDialog(this, "Give a start and end date");
        }
	 
        
        
	  
        
    }//GEN-LAST:event_search1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser d1;
    private com.toedter.calendar.JDateChooser d2;
    private javax.swing.JTable feedB;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton search1;
    // End of variables declaration//GEN-END:variables
}
